### ISSUE TITLE
Can't edit text when link is inline-flex

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1001]
Repro
1. create a link
2. set display inline-flex
3. try editing text- deletion works but you can't type

**Comment by kof** [comment]
Is there a simple fix for this? Otherwise I will deprioritize this one

**Comment by kof** [comment]
Apparently its only impossible to type if the caret is at the end or beginning of the link

**Comment by kof** [comment]
And only if the link is inside a non-flex parent, so it works when parent flex

**Comment by TrySound** [comment]
Looks like I fixed this by making inner paragraph inline and replacing multiple paragraphs with line breaks.
