### ISSUE TITLE
Props panel: basic control types (Switch, Radios, Checkboxes, Text, MultilineText, Select, Number, Color)

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1010]
- [ ] Switch
- [ ] Radios
- [ ] Checkboxes
- [ ] Text (example: ID)
- [ ] MultilineText
- [ ] Select
- [ ] Number
- [ ] Color
- [ ] Make sure to call onChange at `blur` when it makes sense

<img width="263" alt="Screenshot 2023-02-13 at 11 36 52" src="https://user-images.githubusercontent.com/825702/218398031-f9c35163-bb5b-4576-8fcb-c9456832a38f.png">

Design for `Number` is not specified explicitly (I forgot to ask for it), but it's shown here:

<img width="263" alt="Screenshot 2023-02-13 at 11 58 15" src="https://user-images.githubusercontent.com/825702/218401905-69eac9ed-3c73-49cb-abd6-e7596fda3add.png">

**Comment by rpominov** [comment]
Mostly done, but will keep open until I get back from vacation and fix or create issues for remaining things like:

- align `TextArea` with Figma
- align `Select` with Figma
- update / use "Color Picker" for color

**Comment by kof** [comment]
Lets make separate issues and close this one

**Comment by rpominov** [comment]
- #1153
- #1155
- #1154
