### ISSUE TITLE
Props panel: control type "file"

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1011]
- [ ] call it `file` to be in line with storybook
- [ ] add `accepts` option

From DMs:

> We are opening ImageManager when type is file in image-control, we should probaly have file-control instead, that parses "accepts" and decides what to show, image-control etc

<img width="253" alt="Screenshot 2023-02-13 at 12 28 30" src="https://user-images.githubusercontent.com/825702/218407833-5acf575e-9448-4e04-87ad-8d103bd688af.png">

> The button opens the asset picker floating panel. Button text displays the name of the asset chosen.

**Comment by kof** [comment]
We need to think of how we turn src into Source here

**Comment by rpominov** [comment]
Ah, I thought I added this to "Basics", added now: 

> Ability to define a custom label for a prop in component meta (e.g. "Source", "ID")
