### ISSUE TITLE
Doing ZOD validation on import seems like seriously blocks script startup times

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-builder#1051]
Because of that we can't use react-sdk at cloudflare with Bundled/Unbound model and getting 

```
Error: Failed to publish your Function. Got error: Error: Script startup exceeded CPU time limit.
```

see [Worker startup time](https://developers.cloudflare.com/workers/platform/limits/#worker-startup-time) 

Example https://github.com/webstudio-is/webstudio-builder/blob/main/packages/react-sdk/src/components/body.ws.tsx#L62-L64

Having that it's our tool generates all that data we can use zod on write, not on read.

**Comment by kof** [comment]
Also the generated props data shouldn't land in the bundle for workers at all afaik this is not necessary.
