### ISSUE TITLE
List Position Indicator component update

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1066]
Previously used only in the Navigator, now we need another variant of this component to be used in other types of lists. This update is necessary for the Backgrounds section #877, Effects section #879, and more. 

Changes:
- renamed from "Nav Item Position Indicator" to "List Position Indicator"
- created two variants, **with nub** and **without nub** (see component for details)
- refactored previous component to be more responsive (now the nub stays in place when width is adjusted)

<img width="334" alt="Screenshot 2023-02-17 at 1 36 21 PM" src="https://user-images.githubusercontent.com/86495896/219798557-f37be610-bcde-414f-9585-395e2c26d8d8.png">

**Comment by taylornowotny** [comment]
This used to be working in the Navigator but seems like it is not any more @rpominov

**Comment by rpominov** [comment]
> This used to be working in the Navigator but seems like it is not there any more @rpominov

Still works for me:

https://user-images.githubusercontent.com/825702/220623841-f35272f0-2e03-49a5-8947-a92c13037a88.mov

**Comment by taylornowotny** [comment]
Ok good.

We still need to add the variant without the "nub". WIll be used in the Backgrounds section.
