### ISSUE TITLE
Show normal/auto instead of computed value

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1067]
When the value is essentially auto/normal browser default, we should not show a computed value. Computed is still needed for scrub, so the data should stay, but rendering should change.

**Comment by taylornowotny** [comment]
As a rule, we should never show a numerical value with no label on the property.

If a property has a default value, there will be no color on the label and the Input will have placeholder text (placeholder variant).

If a property has a set value, there _must_ be a colored label and the Input will have regular text (set value variant).

Prod:
<img width="219" alt="Screenshot 2023-02-17 at 2 34 30 PM" src="https://user-images.githubusercontent.com/86495896/219808645-eb8959a5-1970-4714-812e-fe570b8f9658.png">

Design:
<img width="334" alt="Screenshot 2023-02-17 at 2 36 40 PM" src="https://user-images.githubusercontent.com/86495896/219809577-efe85ebd-de10-42ad-bbc9-d1fd12251151.png">
