### ISSUE TITLE
New variant for Button component 

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1069]
Added the "gradient" variant to the button component set. Only difference between this variant and primary variant is the background color is the new token: background/gradient/primary (make sure #1068 is merged so the token is available)

<img width="694" alt="Screenshot 2023-02-17 at 3 17 24 PM" src="https://user-images.githubusercontent.com/86495896/219815126-12860fa6-d280-44b1-a194-2ba27e8037b2.png">

**Comment by lokeswaran-aj** [comment]
Hi, @kof I would like to work on this issue
