### ISSUE TITLE
Design update to the Builder UI top bar 

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1070]
Small updates have been made to the top bar and this issue is just to align the appearance in prod with the design.

Updates:
- Publish is a new button variant "brand color" and has a rocket icon (ref #1069)
- Changed color token used for the "on" variant of the "preview" toggle button. Now it's a brighter, more noticeable green.

(preview mode "on")
<img width="345" alt="Screenshot 2023-02-17 at 4 29 34 PM" src="https://user-images.githubusercontent.com/86495896/219821054-ca0d689e-e236-487a-98d4-1f066cf80da3.png">

**Comment by kof** [comment]
Shouldn't the active state of the play button match the publish button at least approximately?

**Comment by taylornowotny** [comment]
Well there's no functional reason that they should be the same color but for aesthetic reasons I tried that and the play icon ends up being too dark. It needs to be a bright color to signify "on". If there's an issue with green we can use blue instead.

**Comment by kof** [comment]
got it, I liked functional similarity of preview mode and production mode

**Comment by taylornowotny** [comment]
Alternatively we can keep the publish button green and give the share
button the gradient. This would signal to the user that there is something
special about the Share feature. If that’s something we want to say then I
can adjust the design accordingly.

**Comment by taylornowotny** [comment]
<img width="965" alt="Screenshot 2023-02-19 at 12 47 46 PM" src="https://user-images.githubusercontent.com/86495896/219974330-6b132de8-7547-4111-97d6-dd35d5b365f2.png">

I left a few options in the design (under "Preview Mode") that you can choose from.

This decision doesn't significantly affect the UX so we are free to go with what we think looks best. My vote is for a green Publish button and a gradient Share button becuase it gives special attention to the Share feature which is a selling point of Webstudio.

**Comment by kof** [comment]
@taylornowotny I agree

**Comment by taylornowotny** [comment]
design updated accordingly

**Comment by kof** [comment]
I think this was done
