### ISSUE TITLE
Update component: Title

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1100]
The Title component was recently updated. Section titles now have states: **open/hover**, **closed**, and **focus**. Clicking a section title should expand/collapse the section. The chevron is gone!

The Title component also includes a "panel with tabs" variant that needs to be built. It contains the new **Panel Tab Trigger** component which has a separate issue #966

https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=0%3A1&t=HLuCPsO7LxFFuq11-1
<img width="1085" alt="Screenshot 2023-02-21 at 4 01 00 PM" src="https://user-images.githubusercontent.com/86495896/220486277-61bb016b-6292-40fa-8975-f5d397869da3.png">

Please let me know if you have questions.

**Comment by kof** [comment]
@rpominov please look into it after properties panel, if its quick to make, lets do it, because its going to clean up the look of the entire style panel.

Additionally I would:
- [ ] persist the open/closed state to local storage (we already have setSetting/setSettings for this)
- [ ] make it open by default

**Comment by taylornowotny** [comment]
To clarify - some section like Backgrounds, will be closed by default, until the user clicks the "+" button in the title to add a background. Then the section will open to show the background that they added. The section design will specify this.

**Comment by rpominov** [comment]
- So sometimes we'll have a "+" button, in which case panel is open when it has items?
- And sometimes we'll have an arrow button, in which case panel is closed by default and can be just opened closed normally?  (Example: "Size" section)

<img width="270" alt="Screenshot 2023-02-22 at 12 43 54" src="https://user-images.githubusercontent.com/825702/220568091-a44ca2d3-628b-49e0-9b11-4f1abefac810.png">

This is kinda confusing. Maybe we should always have an arrow and additionally a plus button sometimes?

**Comment by kof** [comment]
> To clarify - some section like Backgrounds, will be closed by default, until the user clicks the "+" button in the title to add a background. Then the section will open to show the background that they added. The section design will specify this.

@taylornowotny you meant to say they are not closed, but have no items and therefore you only see basically the title container until you add a first item

**Comment by kof** [comment]
@rpominov no, + button is for adding items - for removing items, consistently. The thing about panels like backgrounds and borders is that its a multi-value property and until you have at least one, there is nothing to show.

We have been struggling to find a better option for collapsing ux for entire time and at the end arrived at the same approach Figma has taken.

**Comment by kof** [comment]
Figma doesn't need to collapse items at all, we still have that, just without icons, but using the entire title panel click and cursor as an indicator for clickable behavior

**Comment by rpominov** [comment]
I'm still not sure I understood. Is this correct:

- when a panel contains a multi-value property like background then it's always open, but if it has 0 items it looks like it's closed
- other panels can be opened or closed normally

?

**Comment by kof** [comment]
I would consider a panel always open even if it has 0 items. I think visually there is no difference in that case (@taylornowotny pls correct me if I am wrong)

So items amount doesn't change open/closed state. 
Title panel is a toggle.

**Comment by kof** [comment]
Keyboard accessibility for Panel title should be ([just wrote this in figma](https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE?node-id=2:12361#375746098)):
1. tab focuses panel title, enter would toggle open/closed
2. arrow keys focus buttons inside the panel title, e.g. "+" or others.

**Comment by kof** [comment]
@taylornowotny valid concern here: when backgrounds section has actually items but is collapsed, how does user know it has items without indication?

**Comment by kof** [comment]
@taylornowotny I just realized that a collapsed section with items or definitions can have dots that indicate the content, like in Webflow

<img width="258" alt="Screenshot 2023-02-22 at 10 16 14" src="https://user-images.githubusercontent.com/52824/220591178-6b671095-f181-4ccb-a3fa-9fda956d8f77.png">

**Comment by taylornowotny** [comment]
> Keyboard accessibility for Panel title should be ([just wrote this in figma](https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE?node-id=2:12361#375746098)):
> 
>     1. tab focuses title panel, enter would toggle open/closed
> 
>     2. arrow keys focus buttons inside the panel title, e.g. "+" or others.

Ok agreed. Updated docs accordingly

**Comment by taylornowotny** [comment]
> @taylornowotny I just realized that a collapsed section with items or definitions can have dots that indicate the content, like in Webflow
> 
> <img alt="Screenshot 2023-02-22 at 10 16 14" width="258" src="https://user-images.githubusercontent.com/52824/220591178-6b671095-f181-4ccb-a3fa-9fda956d8f77.png">

I will add this to the component, thanks for reminding

**Comment by taylornowotny** [comment]
@kof @rpominov sorry I didn't explain well enough. Check out this explanation below the title component in the Library page. https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=0%3A1&t=njZAcyw3PGDenWFs-1

<img width="257" alt="Screenshot 2023-02-22 at 10 32 03 AM" src="https://user-images.githubusercontent.com/86495896/220724512-85bfb96b-7bb3-493d-a057-dfed165ca3e1.png">

Sections that do not have a an Add (+) button are open by default. Sections that do have the button are closed by default.

Clicking the title opens and closes the section. The chevron is gone - it's simply not needed.

**Comment by taylornowotny** [comment]
I am now updating the previous designs with the new section title

**Comment by taylornowotny** [comment]
Style panel - Size section open and all others closed
<img width="209" alt="Screenshot 2023-02-22 at 10 53 27 AM" src="https://user-images.githubusercontent.com/86495896/220730418-2e90bef7-68cb-44df-bc68-238c34a25681.png">

**Comment by taylornowotny** [comment]
Added dots!

<img width="995" alt="Screenshot 2023-02-22 at 11 41 34 AM" src="https://user-images.githubusercontent.com/86495896/220741138-a0fec5fd-1aaf-4f04-8043-43e5d47f6d5b.png">

**Comment by rpominov** [comment]
I think I got it now. Sources of confusion for me were:

- I didn't know that closed vs open differ by color of text and button
- I've misinterpreted "by default" in "Sections that do have the button are closed by default". You probably mean "before item are added", but I've read it as "initially as component appears in UI, even if it has items already"
