### ISSUE TITLE
Define a better highlighted color for selected style source

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1108]
This happens when trying to edit the name of a Style Source
![image](https://user-images.githubusercontent.com/122043657/220771953-4d135223-59d3-45de-adef-567886d91ee9.png)

You can't see it, but the name "paragraph" is highlighted
![image](https://user-images.githubusercontent.com/122043657/220772114-b01d909c-d3f8-44e1-bcf5-1e61b47cd366.png)

**Comment by taylornowotny** [comment]
<img width="609" alt="Screenshot 2023-02-23 at 9 05 20 AM" src="https://user-images.githubusercontent.com/86495896/220978530-942b66c7-a461-421f-9175-68741b5df39a.png">

This was designed already, just not implemented. "Editing" is a state on the style source component.
