### ISSUE TITLE
Migrations fail to run

### ISSUE THREAD

**Issue by willopez** [webstudio-is/webstudio-builder#1119]
I followed the instructions on the contribution guide and I got to the following step: 

7. Run `pnpm migrations migrate` - apply database migrations

When I execute that command I see the following error:
```
❯ pnpm migrations migrate

> turbo@0.0.0 migrations /Users/will/code/webstudio-builder
> cd apps/builder && pnpm migrations --dev "migrate"

 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: migrations --dev migrate
spawn migrations ENOENT
 ELIFECYCLE  Command failed with exit code 1.
```

My environment: 

```
node v16.19.1
pnpm 7.27.1
on Mac mini with M1 processor
```

**Comment by willopez** [comment]
got them running.

**Comment by DavithkbY** [comment]
@willopez how did you get them running?

**Comment by willopez** [comment]
@DavithkbY yes I did, updates after I reported the issue resolved this.
