### ISSUE TITLE
Refactor Link component

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1120]
We have 6 link components: (rich-text + regular) * (`<a>` + `<RemixLink>` + "the one that does `preserveBuildParams`")

What should be done:
 - remove "the one that does `preserveBuildParams`" and solve this on `WebstudioComponentDev` level or on data level
 - generate separate props for `<a>` and `<RemixLink>`, so that we can freely change Remix's link props

**Comment by rpominov** [comment]
@kof Probably better to do this after https://github.com/webstudio-is/webstudio-builder/issues/1129 ? Wdyt?

**Comment by kof** [comment]
@rpominov lets hold off on this, #1129 is an entire user story, it has 3 parts, I am not sure which part would be blocking.

This issue also has 2 parts, I think the second part is already defined as part of #1129, bu the first part can be done completely independently

**Comment by rpominov** [comment]
I can do the first part

**Comment by rpominov** [comment]
> generate separate props for `<a>` and `<RemixLink>`, so that we can freely change Remix's link props

@istarkov Could you take this remaining todo from here as part of #1129
