### ISSUE TITLE
Deleting the width prop results in patch error

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1126]
Steps
1. add an image and set prop size to any number
2. delete prop size
3. see patch request fails with 500

When value is deleted from props panel, we send a null and match throws an error

<img width="841" alt="Screenshot 2023-02-25 at 09 08 43" src="https://user-images.githubusercontent.com/52824/221348846-d0a1ea20-074a-4133-94e8-fb305441d723.png">

**Comment by TrySound** [comment]
Looks like fixed already
