### ISSUE TITLE
Position Grid component

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1138]
This grid is used in the Backgrounds feature #877  and in the Size section #1139 and it will be used in future section designs like Effects.

<img width="366" alt="Screenshot 2023-02-27 at 2 04 48 PM" src="https://user-images.githubusercontent.com/86495896/221696401-3da8ced5-e88e-4811-93a7-4234fce70d70.png">

It contains nested grid dot component instances for the dots. This component is also new. Please consider the grid dot as part of this issue.
<img width="437" alt="Screenshot 2023-02-27 at 1 48 23 PM" src="https://user-images.githubusercontent.com/86495896/221693702-7868249b-d06b-4530-9291-6cfb94d5650e.png">

**Description:**
Position can be defined by keywords or values with units, or a combination of both.  

The X axis of the grid represent the keyword values: top, center, and bottom. 
The Y axis of the grid represent left, center, and right.  

The Position Grid will always be displayed next to two input fields, labeled top and left (see examples). These allow the user to specify the Y coordinate relative to the top edge and the X coordinate relative to the left edge.

The inputs will reflect the selected position of the grid. (e.g. Top-left position selected = Top: 0% and Left 0%. Bottom-right position = Top 100% and Left 100%)  If a value other than 0, 50, or 100 % is specified in the input, remove the selected position from the grid. 

See the component in the Library file for examples and more details.

It's pretty much a copy of similar control in Webflow so please use those as a reference if my descriptions are unclear.
<img width="232" alt="Screenshot 2023-02-27 at 1 20 11 PM" src="https://user-images.githubusercontent.com/86495896/221688138-b10ec432-369c-466d-aecc-b4297c7dbf41.png">

Ref:
https://developer.mozilla.org/en-US/docs/Web/CSS/object-position

Anatomy:
<img width="395" alt="Screenshot 2023-02-27 at 1 43 18 PM" src="https://user-images.githubusercontent.com/86495896/221692884-54541f1f-14c7-457c-8aec-9cbce8b67050.png">

**Comment by taylornowotny** [comment]
made a supplemental video explanation - hope it helps!
https://share.descript.com/view/Y04r3LkycoK

**Comment by kof** [comment]
@taylornowotny  I think we should add the value from floating panel to the style panel so if I want to know the current position - I don't have to open the panel

**Comment by taylornowotny** [comment]
Ok let’s consider that for the next iteration. I would probably display the
value online as you would see it on CSS but there are some challenges with
that.

**Comment by kof** [comment]
Closing it as done, please reopen if you think its not done
