### ISSUE TITLE
Controls width in props panel use values not from our spacing units: 98 and 120

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1150]
@taylornowotny Not sure if this is intentional. If intentional we can keep these IMO.

<img width="319" alt="Screenshot 2023-03-01 at 16 19 06" src="https://user-images.githubusercontent.com/825702/222137410-6a2fcbd7-3505-4f23-baaa-1e639fb43056.png">

https://github.com/webstudio-is/webstudio-builder/pull/1134#discussion_r1121603921

**Comment by taylornowotny** [comment]
Yea it’s intended. ID is on every element and should be as long as
reasonable to accommodate longer strings. The width and height only need to
store max ~5 digits. The width and height should be the same size by
there’s no need for them to match the ID field.

**Comment by rpominov** [comment]
Sorry if the question ended up confusing. What I was trying to ask is why we use 98 and 120 that are not in this scale?

![image](https://user-images.githubusercontent.com/825702/222490510-780647f5-3655-4dd3-a79f-5172a8f011e8.png)

**Comment by taylornowotny** [comment]
Oh thank you for catching that, it was a mistake on my part. Adjusted to
144px and 96px to fit the scale.

**Comment by taylornowotny** [comment]
Ah that answers why it was so short to begin with, sorry I forgot. Adjusted
to 112px
