### ISSUE TITLE
Border section

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1169]
<img width="341" alt="Screenshot 2023-03-02 at 11 42 50 AM" src="https://user-images.githubusercontent.com/86495896/222536283-35ed0054-8978-4912-8c0d-79a080230307.png">

Nice and simple, this one. We may add more properties to this section in the future but this UI should cover 99% of uses.

Icons are in-progress - ask me if there's anything not obvioous

**Comment by istarkov** [comment]
I would implement in few steps as like as backgrounds.

1. Having that `+` section title is not merged. I would make initially this 
Border Style  is added as no other way to set it up
<img width="239" alt="image" src="https://user-images.githubusercontent.com/5077042/226685199-384236f6-0007-46b3-9abb-4d0b99b81016.png">

- [ ] - After + section merge make it like in figma
