### ISSUE TITLE
Link Block component

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1173]
To have a link that can contain instances instead of text we need a non-editable link block component.

**Comment by jakobsturm** [comment]
Hey @kof,

what happened to this component? I can't find it anywhere. Would be amazing to just create a link without having to delete the text all the time (e.g. to wrap an image).

Appreciate it! Thanks!

**Comment by kof** [comment]
@jakobsturm wdym Link component has always been just one component, you digged an issue with a name that was never used in webstudio

**Comment by jakobsturm** [comment]
Sorry for the confusion, coming from Webflow land hehe. In Webflow there is a Link and a Link Block component. The Link component comes with text, the Link-Block component is just an empty <a> tag to wrap an image or a block. In Webstudio, if I am not mistaken, the Link component always comes with text.

**Comment by kof** [comment]
Link can do both here. Like a anchor tag in html.

**Comment by jakobsturm** [comment]
Yeah I am aware of that, just thought there was a way to save a few clicks and have an empty Link Block instantly to wrap something. But thanks for the clarification :)

**Comment by kof** [comment]
If you make a page with style guide, probably copying from there, would save you a lot of time

**Comment by jakobsturm** [comment]
Great idea - thanks :)
