### ISSUE TITLE
Assets path must not contain bucket domain

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-builder#1179]
We inject it here https://github.com/webstudio-is/webstudio-builder/blob/123cdb96fa6cbdf5f8edb8be63d5ad01b080d9c0/packages/asset-uploader/src/utils/get-asset-path.ts#L8

The issue is that this path depends on app.

On published projects, it must be on the same domain i.e. 

`/cgi/image/{...transform}/{imageurl}` for transformed images  (where imageurl is relative bucket path without domain)
and `/cgi/assets/{fonturl}` for fonts and svg ({fonturl} is relative bucket path without domain)

On Vercel saas deployment, it must be

`image-transform.wstd.work/{...transform}/{imageurl}`
`assets-dev.webstudio.is/my-super-font.ttf`

Also, it's an error to use process.env inside libraries like here https://github.com/webstudio-is/webstudio-builder/blob/123cdb96fa6cbdf5f8edb8be63d5ad01b080d9c0/packages/asset-uploader/src/utils/get-asset-path.ts#L5-L6

All process.env must be at the app level. Only `NODE_ENV` is allowed in libraries.
The app should define how to create/generate paths for assets.

As of now in published apps, we replace hostname with pathname which is a hack, and should be removed. See https://github.com/webstudio-is/webstudio-saas/pull/96 for cleanup

**Comment by TrySound** [comment]
This is done, need to implement on saas side.
