### ISSUE TITLE
Collapse detector fails on initial load in this particular case

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1183]
<img width="489" alt="Screenshot 2023-03-06 at 23 49 54" src="https://user-images.githubusercontent.com/52824/223273398-bda8765e-abf3-4717-be38-cd46338ea3cc.png">

Link to page in DM

Steps

1. open debug page
2. on initial load collapse detector sets both vertical and horizontal paddings
3. if you change any CSS property, it detects correctly and padding goes away
4. after reload it will be back

**Comment by istarkov** [comment]
I'm pretty sure that its related to this https://github.com/webstudio-is/webstudio-builder/issues/1159

**Comment by istarkov** [comment]
TODO: 
- [ ] - intercept on resize (debounced)
