### ISSUE TITLE
Selecting paragraph text is difficult sometimes

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1193]
Doesn't happen all the time, just sometimes, but selecting paragraph text can get finnicky.

https://user-images.githubusercontent.com/122043657/223572083-654a81e9-f169-4232-9a67-b640f7a6ffa2.mp4

**Comment by kof** [comment]
I just looked at it and I can't understand what you are doing exactly and what happens, please either talk over the video or describe exactly what you press when and what happens sometimes
