### ISSUE TITLE
Backgrounds "Reset" info text repeats a bunch of times

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1218]
1. Add a new layer to "Backgrounds"
2. Click on the "none" property
3. Under the reset button "Resetting will change to initial value" is repeated a bunch of times
![image](https://user-images.githubusercontent.com/122043657/224164803-14fe7494-8a7e-4212-880b-c9028514d731.png)

**Comment by istarkov** [comment]
resolved
