### ISSUE TITLE
When in preview, external links should open in new window

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1231]
<img width="147" alt="Screenshot 2023-03-13 at 14 39 40" src="https://user-images.githubusercontent.com/825702/224678407-8720bc6e-b16e-4dd2-92c9-1d9ed52f41a4.png">

It the preview mode, which you get in by clicking "play" button above, there should be special behaviour for links. We should:

1. Either switch page: when link corresponds to a page, no matter what "target=" says
2. Or open link in a new window (tab): when it's an absolute link

**Comment by rpominov** [comment]
A question is what should happen if it's a relative URL that doesn't correspond to a page. I think we should ignore clicks on such links when in preview. @kof wdyt?

**Comment by kof** [comment]
We could try to resolve it and see if it matches an internal page, so in the end its just like page link

**Comment by rpominov** [comment]
Yeah, but what if it doesn't match?
