### ISSUE TITLE
Style Sources - show "remote" labels

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1241]

**Comment by kof** [comment]
I think what you mean here is one of the todos " orange property label (remote) for not selected style source"  in https://github.com/webstudio-is/webstudio-builder/issues/807

please reopen if you mean something else 

basically when value is defined on one token but another token was selected, property label should be orange

cc @TrySound

**Comment by taylornowotny** [comment]
Yes @kof that's what this issue is for, I just got distracted before writing the description for this issue. Is this redundant with issue #807 or do we need this issue?
