### ISSUE TITLE
Remove select menu button from Color inputs

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1247]
@istarkov I appreciate your feedback that you want to include this button, but after consideration I am realizing that it is not ideal. We will continue to support CSS colors via typing and autocomplete.

- [ ] Please remove the nested select menu button from both the background-color field and the text-color field. The text color button doesn't work anyway.

**Design rationale:** The detriments of including this button outweigh the benefits. The menu is easily available even without the button.

Pros of including the select menu button:
- provides fastest access to the CSS colors menu

Cons of including the select menu button:
- The list is huge, so it's not very practical to use.
- The list shows anyways when the input is focused and there is no current value or the value is deleted.
- The button reduces the amount of space available for the color name within the input.

**Comment by kof** [comment]
he used CssValueInput control which has 2 modes: keywords and units. When in keyword mode there is always that arrow button. When in unit mode there is always the unit button. I don't want to add a 3rd mode where we have keywords but no arrow button. This would add too much in complexity and general understanding when is supposed to happen what.

I see only 2 options: leaving it as-is or removing the keywords from color. 
I don't see huge value in colors autocompletion tbh.

**Comment by kof** [comment]
Unless you want to remove the arrow button from all cases, so when its in keyword mode it never shows the button at all. That wouldn't complicate things in that case, but then why did you want it there initially in the first place?

**Comment by taylornowotny** [comment]
Yes there are many cases where we want to have keywords available via autocomplete but not a select menu.

Examples:
- when we have both keywords and units. Currently choosing a keyword will remove the unit select and replace it with a keywrod select. This is not ideal.
- this color input, for reasons detailed above

**Comment by taylornowotny** [comment]
Does this need to be a separate issue?

**Comment by kof** [comment]
So the logic would be: when there is units menu, we always show units trigger, autocomplete has no trigger, but when there is autocomplete only - we show trigger?

**Comment by kof** [comment]
It feels like we need to decide how to handle the "some keywords" in units list problem before changing this, because they are also related and doing just this would be half-backed.

**Comment by taylornowotny** [comment]
Yes. This has come up a few times. As far as I can tell this is still the ideal behavior:

- When there is a units menu, always show unit menu trigger
- When a keywords menu is specified by the design, we show a keyword menu trigger
- In all cases where keywords are allowed, keywords can be added via autocomplete (when there is no value in the input and the input is focused, the whole autocomplete menu shows. This is current behavior & it's good.)
- "Auto" and "None" are allowed to be in the units list, no other keywords
- When any keyword is in an input with a unit list, the unit is unitless. It's important to still show the unit so the user can still access the menu.

Any objections?

**Comment by taylornowotny** [comment]
We could omit "Auto" and "None" from unit menus - I understand that this doesn't seem very consistent. But this is what Webflow does and I have never had an issue with it. They don't have autocomplete though.

**Comment by taylornowotny** [comment]
It would be possible to have both menus at the same time and I designed a pattern for that, but I want to avoid this becuase it further limits horizontal space and it looks awkward since units aren't applicable to keywords and vise versa. We definitely can't hide the triggers under any circumstances.

**Comment by kof** [comment]
As a thought experiment, what would happen if user enters some keyword and then selects some unit, what would happen? 

Currently, this is impossible because you can't set a unit on a keyword and when you start entering non-numeric input we switch into keyword mode.

We are currently clearly separating unit and keyword modes. What you are proposing seems like a mixed mode.

**Comment by taylornowotny** [comment]
A mixed approach is appropriate, becuase some CSS properties can have both keywords and unit values.

When a keyword is applied and user selects a unit, we can simply remove the keyword and replace it with a 0. Webflow does the same.

Even better would be to remember the most recent numerical value on the input so if the user adds a number value, then changes to keyword, then selects a unit, the previous number value is there. That's not critical but users would appreciate it.
