### ISSUE TITLE
Improve menu UX with a safe area

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1270]
I read an article from Linear about how they added a "safe area that lets you move the mouse along the shortest path without closing the sub-menu"

<img width="905" alt="Screenshot 2023-03-20 at 1 24 00 PM" src="https://user-images.githubusercontent.com/86495896/226457223-3b8bca8d-c8cb-44ce-8614-0c07a1eb684c.png">

The article explains the logic and how to built it in react:
https://linear.app/blog/invisible-details

Can we add this to our menus? 🙏

**Comment by rpominov** [comment]
I think Radix UI that we use for menus already does this

**Comment by taylornowotny** [comment]
Yes you are right, that's why I closed this issue. I would delete it but I couldn't figure out how
