### ISSUE TITLE
When copying instances between projects, references to Assets and Pages are broken

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1325]
Depends on: #1335

- [ ] Create a corresponding Asses for `Image.src`
- [ ] Create a corresponding Asset for fonts (`fontFamily`)
- [ ] Handle `Link.href` somehow (see what Webflow does)

The list above are just examples. Need to handle all references to Assets or Pages in props or style.

https://discord.com/channels/955905230107738152/1090935034657120286

**Comment by rpominov** [comment]
When copying a link Webflow clears `href` and shows this warning:

<img width="274" alt="Screenshot 2023-03-30 at 14 40 37" src="https://user-images.githubusercontent.com/825702/228811616-b7f126d9-1856-423c-a607-584f7555106b.png">

**Comment by kof** [comment]
seems like we can fix this now since https://github.com/webstudio-is/webstudio-builder/pull/1376
