### ISSUE TITLE
Default box size doesn't count in preview

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1328]
https://user-images.githubusercontent.com/122043657/228986121-81f9a787-ecaf-4f46-97c6-48c16ac7e7e5.mp4

I made an example in the debugging page in the builder

**Comment by kof** [comment]
This is expected, same happens in webflow. Box itself collapses without content, we artificially place some height in builder to let user see it and use it, but if it has no content or nothing that gives it some size - it will collapse, that's the browser behavior.

We have already discussed an option to set some width/height by default, but that would mean user would have to unset it every time
