### ISSUE TITLE
Link text doesn't count padding in its size value

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1329]
https://user-images.githubusercontent.com/122043657/228986400-08f8d4aa-26e0-4b80-a18c-1cc0b2795ec2.mp4

I made an example in the debugging page in the builder

**Comment by kof** [comment]
This has to do with box-sizing content-box (section other). In the upcoming CSS normalize we will set all elements consistently to box-sizing border-box cc @istarkov @TrySound 

https://github.com/webstudio-is/webstudio-builder/issues/473
