### ISSUE TITLE
Button component is a different size than link block component, even with the same styling applied

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1330]
https://user-images.githubusercontent.com/122043657/228986570-e9c673a3-d3dd-42ae-9190-97984a1dc127.mp4

I've made an example in the debugging page in the builder

**Comment by TrySound** [comment]
Please share the link to the project and page

**Comment by markxtang** [comment]
It's in the same file as the Webstudio Website, I made a page called **Debugging***

**Comment by kof** [comment]
Button has some more padding by default, have you tried setting it to 0?

**Comment by kof** [comment]
@markxtang  check again in prod, we released a normalize that should have put box-sizing border-box on both, whish should have fixed the issue you were seeing

please reopen the issue if not fixed
