### ISSUE TITLE
Add figcaption support

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1377]
To give attribution to images, html provides figure and figcaption elements. While box allows to use figure, we don't have a way to use figcaption.

I think maybe Text component should allow selecting figcaption as a tag. Additionally lets look for other useful use cases for tag list in Text component.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

**Comment by taylornowotny** [comment]
Sounds good. Doesn't seem like we need any special UI for this, just a tag option on the Text Block component

I'm sorry that I don't have suggestions for other Text tag. Webflow doesn't have this so I have no experience with using it
