### ISSUE TITLE
Display: Flex section and Flex Child design QC

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1411]
This section needs a lot of work to align with the design. This is a high priority becuase it's one of the designs that we are most proud of and we will be showing it close-up in our first promo video.

The design docs are super thorough and clear so please read them carefully and if you see more differences than are listed here it would save time to correct those proactively.   https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=12%3A1688&t=cODzF127rEwIDvT6-1

Major differences:  
- [x] Flex Control Grid styles have many differences from the design. Please inspect the design and read the design docs carefully and make all corrections. There are too many small differences to list. The main issue is that the bars don’t align over the dots like they do in the design. The design is carefully formatted so please copy the design precisely so it all aligns correctly. ...
- [ ] ... The hover styles might be a bit complex so those can wait until later.
- [ ] Flex-gap controls are using a keyword menu. In the design it is a units menu. 
- [x] All icons are wrong, including in the flex-child section.  
- [x] Missing hover styles on the gap link. This is supposed to be a “small toggle button” component.  
- [x] Flex-direction and flex-wrap currently open a dropdown menu. The design calls for toggle buttons that swap between two values. No menu. Icon changes on toggle.  
- [ ] The menu items for align-items and justify-content should be “menu item large” components. They should be colored when an item is selected as described in the design.  
- [x] The display menu should list the options in the design. They are: Block, Flex, Inline Block, Inline, and None. 
- [x] Alignment and spacing is not consistent with the design - compare with the Anatomy sections in the design docs.

The toggle group component also needs some style adjustment but I made a separate issue for that: #1410

I'm happy to support you in any way so don't hesitate to ask any questions you may have.

**Comment by taylornowotny** [comment]
If we are pressed for time, the first priority should be updating the icons and the flex grid lines becuase these will be featured in the product hunt video

**Comment by rpominov** [comment]
> Flex-gap controls are using a keyword menu. In the design it is a units menu. 

Not sure I understand this one. 

The control has both unit and keyword menus. Unit menu is open when you click on a the unit, and keyword menu is open when you start typing a keyword.

Same as all our CSS value inputs.

**Comment by kof** [comment]
He is talking about gap being initially in unit mode 

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=252-32534&t=qn1to2TB2dWxNong-4

<img width="257" alt="Screenshot 2023-04-24 at 13 29 28" src="https://user-images.githubusercontent.com/52824/233983776-585f7583-92a6-4941-ab5e-fb93aa486eae.png">

**Comment by kof** [comment]
The problem here is that by spec, gap is Normal initially, not 0 like webflow has it. But 0 is more practical, because you will always want to change it to something numeric.

At the same time we have the same question to answer for width and others. E.g. width has initial auto and webflow shows auto.

They are being inconsistent @taylornowotny

**Comment by rpominov** [comment]
Ah, I saw the comment about "Normal" in Figma, but wasn't sure this TODO item is about the same as it talks about menus specifically.

So, are we in agreement that "Normal" should correspond to an empty field as described in Figma? 

<img width="456" alt="Screenshot 2023-04-24 at 15 07 46" src="https://user-images.githubusercontent.com/825702/233991583-c45b4378-afe4-4aec-a3f4-8dd4148be498.png">

**Comment by kof** [comment]
Webflow uses placeholder in cases of normal/auto/none, so value can be blank indeed while these are set as a placeholder to indicate what the current state is

**Comment by rpominov** [comment]
Moved remaining to-dos into separate issue #1532

**Comment by rpominov** [comment]
> All icons are wrong, **including in the flex-child section.**

Just realised I was supposed to also update icons in flex-child. Will do a PR today.
