### ISSUE TITLE
opening properties of blockquote shits the bed

### ISSUE THREAD

**Issue by ninoppp** [webstudio-is/webstudio-builder#1418]
In a test project, making a blockquote, selecting and then selecting properties gives error:
![image](https://user-images.githubusercontent.com/101364396/231312105-f6cb6282-858f-48dd-a271-a9b02dc41632.png)
Same if I select properties on the body before selecting the blockquote.

**Comment by ninoppp** [comment]
that was fast

**Comment by kof** [comment]
releasing within the next hour
