### ISSUE TITLE
It is possible to download metadata of other user' instances

### ISSUE THREAD

**Issue by ggurgone** [webstudio-is/webstudio-builder#1448]
While testing some changes to the [webstudio CLI](https://github.com/webstudio-is/webstudio-cli) I noticed that it is possible to dump data from any Webstudio instance.

The expected behavior is that I would need a valid auth token for the project in order to be able to dump the data.

To reproduce install the CLI:

```
npm i -g @webstudio-is/cli
```

Sync any instance:

```
wstd sync <project id> --host <instance url>
```

The result would be in the `.webstudio` folder.

**Comment by kof** [comment]
This has been resolved, no? Please reopen if still relevant

**Comment by istarkov** [comment]
Not resolved, reopen

**Comment by istarkov** [comment]
resolved now
