### ISSUE TITLE
Navigator drag flickering

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1457]
https://user-images.githubusercontent.com/86495896/232105313-b0b88501-6ca9-4234-acc2-c48b1f979b33.mov

It's hard to describe what's going on here but I hope it's clear enough from the video. basically when dragging a Nav item to a new position, the indicators flicker back and forth briefly in between positions. I would expect to see a smooth transition.

**Comment by rpominov** [comment]
Seems like we broke edge detection somehow. Will fix
