### ISSUE TITLE
Nav item, Page item, and Font item padding adjusted to make space for scroll bar

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1458]
<img width="710" alt="Screenshot 2023-04-14 at 5 15 59 PM" src="https://user-images.githubusercontent.com/86495896/232173171-5d70d1a8-ca5a-435d-a806-100f368dbcde.png">

The Nav item, Page item, and Font item components have been updated.

There is only one change. Right padding was 8px, it is now 14px. Left padding stays at 8px.

See an example of these panels with a scroll bar at the end of the Builder UI docs page: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=1610%3A39616&t=Xu45Gsk5F1fI4w7T-1

**Comment by kof** [comment]
@rpominov once spacing is adjusted we can use ScrollArea for scrolling, so that its consistent
