### ISSUE TITLE
Breakpoint cascade indicator line update

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1460]
- [x] Add radius. You were right @kof this is more consistent with our overall design aesthetic (design is updated)

- [x] Adjust Base indicator behavior:
Previously we had said the indicator line should, "use both cascade indicators together to cover the whole range of bp toggles and let the center point where they meet be the center of the base bp toggle btn".
This results in a beautiful appearance when there are bps on either side of base, but if there are only max-width or only min-width breakpoints then the gradient looks off-center with this approach.
If possible, it would be preferable to use a single indicator line in those cases for a better appearance.

In summary we want to change from this (current):
 <img width="235" alt="Screenshot 2023-04-14 at 5 46 03 PM" src="https://user-images.githubusercontent.com/86495896/232174830-497c227d-9e71-450d-b066-4ebafd2b1b09.png">
  to this:
 <img width="270" alt="Screenshot 2023-04-14 at 5 46 26 PM" src="https://user-images.githubusercontent.com/86495896/232174833-2f47f12a-5819-41d6-8fdf-b747f0b9f435.png">
The design has been updated with new instructions: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=3692%3A50484&t=Xu45Gsk5F1fI4w7T-1

- [x] Adjust animation on base:
The cascade indicator animation looks excellent on all other breakpoints. When you select a larger bp the indicator grows, and when you select a smaller bp it shrinks. But on base the two cascade indicators meet in the middle and it looks inconsistent.
Can we please adjust this so it animates the same on base as it does on the other breakpoints?

If any of this was not clear from my explanation I'd be happy to talk about it more.

**Comment by kof** [comment]
Regarding animation: seems consistent to me, it meets in the center just like when it goes to the middle when you hit breakpoint closer to the middle. In any case it seems its not worth discussion, since it looks good.
