### ISSUE TITLE
Implement Panel tabs design

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1462]
The design of the tabs for the right side panel needs to be implemented. This includes layout, text style, and states of the Panel Tabs List and Panel Tab Trigger components.

See them in the Library file: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?node-id=0%3A1&t=K0bGMeRqyxlyA88z-1

Design:
<img width="648" alt="Screenshot 2023-04-15 at 10 16 52 AM" src="https://user-images.githubusercontent.com/86495896/232242128-a1e1e7e0-d6be-4bf8-95f1-ac48acb2d126.png">

Prod:
<img width="248" alt="Screenshot 2023-04-15 at 10 15 38 AM" src="https://user-images.githubusercontent.com/86495896/232242184-f0c2c751-c655-4722-8ee2-c5bb3a719282.png">

**Comment by kof** [comment]
@rpominov wasn't this already done?

**Comment by rpominov** [comment]
Yeah. There were 2 issues about it. I guess this is third duplicate :)

https://github.com/webstudio-is/webstudio-builder/issues/966
https://github.com/webstudio-is/webstudio-builder/issues/1643
