### ISSUE TITLE
Ability to link to a section on a specific page

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1475]
Context: https://github.com/webstudio-is/webstudio-builder/pull/1454#issuecomment-1511164203

We should consider an ability to create a link to a specific section on a specific page. Perhaps have a section picker next to the page picker here:

<img width="530" alt="Screenshot 2023-04-17 at 14 54 21" src="https://user-images.githubusercontent.com/825702/232476814-ae447efe-1a9e-4b12-8cec-204304abc5a1.png">

**Comment by kof** [comment]
@taylornowotny  What webflow does we can also do, but that's bad, because its hardcoded, if your id changes, url will break.

Instead we should move the section link into the page tab and allow using it with or without selected page, when page is not selected, it should be considered current page

@rpominov additionally it is better to use a fullurl + hash always, because this way if link is rendered using slot on a different page, the link still works,so better always by default /webstudio.is#section

**Comment by taylornowotny** [comment]
<img width="409" alt="Screenshot 2023-04-17 at 2 12 51 PM" src="https://user-images.githubusercontent.com/86495896/232612376-2555eafb-5336-41ad-b6af-2df78b9e8d6e.png">


@kof is there a reason we can't just add a page picker to the section link tab? This is a better UX becuase if we go with your suggested pattern, users who want to link a section will have to know to look in the page link tab and users who want to link to a page will have to deliberately ignore the section select menu.

**Comment by kof** [comment]
@taylornowotny its all about the tab icon for page and section, right? I think section icon is anyways not something people will know and recognize and page is enough of a hint.

see section link this way: section hash is basically part of the url, which is page url + has, it literally is this: https://webstudio.is#some-secection

It totally makes sense that both can be in one tab, the separation webflow has is dumb

**Comment by taylornowotny** [comment]
Ok I will adjust the design accordingly

**Comment by taylornowotny** [comment]
<img width="296" alt="Screenshot 2023-04-17 at 2 43 26 PM" src="https://user-images.githubusercontent.com/86495896/232617492-91f358fd-0bad-4d79-8abf-61366910123f.png">
updated

**Comment by kof** [comment]
Nice, looks better, cleaner and way more powerful, @rpominov this is ready

**Comment by kof** [comment]
@rpominov I am putting it on prio 2 as this is not blocking anything, but if its something you can do within hours, then lets do it

**Comment by rpominov** [comment]
@taylornowotny

Regarding:

> Instead we should move the section link into the page tab and allow using it with or without selected page, when page is not selected, it should be considered current page

We talked with @kof and decided to show placeholder text "Current page" instead of "Choose page" when no page is selected. 

This way user will understand that they're selecting a section on the current page when they go straight to selecting a section without selecting a page first.

Hope that's ok.
