### ISSUE TITLE
Add category label for component states in the list

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1518]
We want to be able to differentiate whhich state is css standard and which is custom, because it's possible to get :active and Active in one instance

**Comment by taylornowotny** [comment]
<img width="427" alt="Screenshot 2023-04-22 at 11 29 39 AM" src="https://user-images.githubusercontent.com/86495896/233800752-5fe07179-ed9e-43a1-9ed0-011af81b19c7.png">

Differentiation achieved with separate categories. Added to "States" frame of "Style Sources" Design Docs.
