### ISSUE TITLE
Component state system

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1529]
We want a state system for components, similar to React's `useState`, but while in builder show state in a panel similar to props with bidirectional connection:
 - user may change state via panel,
 - component may change its own state and it will be reflected in the panel.

We will safe state in DB, but only for convenience. In the published site only the component will manage its state, and state from DB wont be used.

In code it may look something like this:

```js
import { getInstanceIdFromComponentProps, useState } from "@webstudio-is/react-sdk"

export const MyComponent = (props) => {
  const [state, setState] = useState(getInstanceIdFromComponentProps(props));

  // ...
}
``` 

- [x] Express from component meta available states, similar to props
- [ ] UI in settings for state is reusing props controls
- [x] We create a state tree JSON just like props
- [x] We use nanostores to subscribe the state in each sdk component that needs state
- [x] We allow both component and the UI to control the state
- [x] First practical use case is to allow switching between initial, error and success states of the form using states instead of props

More context: https://discord.com/channels/955905230107738152/1100515833593221150

**Comment by TrySound** [comment]
Let's have separate discussion for ui
