### ISSUE TITLE
Two instances of a component are added

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1544]
https://user-images.githubusercontent.com/825702/235429630-e756a9dc-5928-4c06-8369-e44a0ca20683.mov

- Start adding a component by dragging
- Drag just a little to make sure cursor is still in the same area where the component card was
- Drop
- Two instances of the component get added (probably both drag and click on the card get handled)

https://discord.com/channels/955905230107738152/1100689716128522310

**Comment by kof** [comment]
seems to be fixed, please confirm

**Comment by rpominov** [comment]
Yes. Can't reproduce now
