### ISSUE TITLE
Register components in canvas and sync to builder via atom

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1545]
Currently we call this in builder:

```
registerComponentMetas(customComponentMetas);
registerComponentPropsMetas(customComponentPropsMetas);
```

But this is wrong because we want Canvas to be responsible for components and tell Builder which components are available and their metas. We can sync this data via atoms as everything else.

Additional issue is that `{Icon: SomeIcon}` that we have in meta cannot be send trough `postMessage`, we would need to switch to SVG strings for component icons.

https://discord.com/channels/955905230107738152/1102522268594212955

**Comment by kof** [comment]
Additionally we need to decide if meta should be serializable or not. Fundamentally the problem with Icon component is that its not a JSON-serializable. There are potential future features that will also have the same issue.

We use icons package for sdk components, though maybe sdk components should have their own icons, even if its in some cases going to be duplicated in icons package.

Ultimately component icon should be controled by the component author, not by builder.

We could provide a base64 version as a string for example.
