### ISSUE TITLE
Separate component label in panel and initial name of the instance

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1551]
Currently both **component label in panel** and __initial/default name of the instance__ come from `meta.label`, we should add something like `meta.defaultInstanceName`.

- [x] Separate the labels
- [ ] Set `{label: "Checkbox", defaultInstanceName: "Checkbox Field"}` for the `CheckboxField` component
- [ ] Set `{label: "Radio Button", defaultInstanceName: "Radio Button Field"}` for the `RadioButtonField` component

**Comment by kof** [comment]
Please check the actual names again with @taylornowotny and figma

**Comment by rpominov** [comment]
The ability to have separate labels is added. 

And the other 2 todo items are outdated (we decided to use different names, and already did).
