### ISSUE TITLE
Html component

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1563]
For embedding custom html we need to allow user pasting any random code. While this is generally bad, we can't disallow it.

**Comment by taylornowotny** [comment]
Embeds can be used for many things, from simple SVGs to embedding 3rd party services like maps, forms, and sliders.

For those third party services, you often need to paste some code in the head or foot of the page (inside <head> and at the end of <body> respectively).

Webflow has a section for this in page settings.
<img width="658" alt="Screenshot 2023-05-04 at 9 23 48 AM" src="https://user-images.githubusercontent.com/86495896/236265189-e6ab896d-3a80-47e5-bc6a-a6249e4d6215.png">

Can we add this as part of the same issue?

The UI should be super simple, just a title, description, and a code area that is practically the same as the embed code area.

**Comment by kof** [comment]
Btw we should support svg natively, when user pastes svg, each path inside would be selectable and stylable.
