### ISSUE TITLE
Bug report tab in the toolbar

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1571]
I've designed the icon and position for the bug report tab trigger. You can see it in context here: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=1610%3A39616&t=KNZBcIPWBlSmY6gK-1

<img width="575" alt="Screenshot 2023-05-04 at 10 02 24 AM" src="https://user-images.githubusercontent.com/86495896/236275092-92536f76-3f90-446a-9149-cdad4f185f19.png">
<img width="326" alt="Screenshot 2023-05-04 at 10 02 10 AM" src="https://user-images.githubusercontent.com/86495896/236275097-dd71d192-677d-4c27-ace1-e5586c057e29.png">

@kof It's up to you what approach you want to use for the actual bug report. If it's a 3rd party service within a window, ideally that would be inside a Webstudio floating panel with a title component with a close button.
If there's any more design than that to be done on this window, just let me know what you need and I'll do it quickly.

**Comment by taylornowotny** [comment]
BTW I will adjust the icon artwork later today if I can find the time. It could look nicer but it's ok for now.

**Comment by kof** [comment]
done
