### ISSUE TITLE
Allow submit only if form exists

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#1611]
We need to check that there's a form on the page before handling it's submit at backed.

See: https://github.com/webstudio-is/webstudio-saas/pull/148#discussion_r1188589370

**Comment by kof** [comment]
Probably not just any form, but a specific one? maybe you need a hidden hash that is sent along with it? Are there some good practices around verification of a valid form?

**Comment by rpominov** [comment]
Yes, we identify form by id that we send in a hidden input

**Comment by kof** [comment]
Is it the same as form instance id? So it could be used to identify if the instance of that form is on that page? You can have many forms on the same page

**Comment by rpominov** [comment]
Yes, it’s the instance id. We find corresponding form in the tree of the
page
