### ISSUE TITLE
Match design of Panel Tabs List & Panel Tab Triggers

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1643]
Please review the design of Panel Tabs List & Panel Tab Trigger components and update the styles in code accordingly.

<img width="865" alt="Screenshot 2023-05-17 at 9 37 11 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/d0066ac8-6c87-45bd-a567-b18f4016c8b3">

Differences that I noticed:
- [ ] States (hover, focus) not implemented
- [ ] Text styles are incorrect
- [ ] Spacing and sizing is totally incorrect

**Comment by rpominov** [comment]
Seems like a duplicate of https://github.com/webstudio-is/webstudio-builder/issues/966
Going to do this soon
