### ISSUE TITLE
New button variant: neutral-destructive

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1645]
This variant is useful for destructive actions when a red button would be too visually prominent. It is nothing more than a neutral button with red (foreground.destructive) text & icon.

This is used in the Publish UI and will probably be needed elsewhere in the future.

<img width="370" alt="Screenshot 2023-05-17 at 10 41 27 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/85e5b951-1282-4907-bf59-a0b406b27260">

<img width="818" alt="Screenshot 2023-05-17 at 10 55 42 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/0e016ee3-67de-4c66-ad3a-5aaeff2c4da0">

Link to Library file: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=2%3A4852&t=AZLy0kBDug8h3vX7-1

**Comment by rpominov** [comment]
@istarkov Will you do this, or do you need my help?

**Comment by istarkov** [comment]
I will
