### ISSUE TITLE
Confirmation dialog for design token deletion

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1672]
It's not obvious to the user that delete menu option will delete the token. from all instances. It's an equivalent to cleanup. We should add a confirmation dialog before removing it.

"Design Token 'x' will be deleted from all instances, continue?"

**Comment by taylornowotny** [comment]
How about "Delete [token] from the project including all of its styles?"

or "...from the project and remove its styles?"

**Comment by kof** [comment]
Does it communicate the fact that it will be removed from all instances?

**Comment by taylornowotny** [comment]
Saying "from the project" communicates that but avoids the word "instances" because it may not be universally understood and I don't think it's used anywhere else in the UI.
