### ISSUE TITLE
Heading text edit bug

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1698]
`Delete` `Backspace` `CTRL+X` and `CTRL+V` cause the window to jump when editing Heading text

https://github.com/webstudio-is/webstudio-builder/assets/122043657/a0fce189-7c6a-425e-9868-47ab610fc867

**Comment by kof** [comment]
@TrySound looks like the same as I had recently reported https://share.descript.com/view/fnLkvPrdCjb

**Comment by TrySound** [comment]
Can reproduce it only in safari. Chrome works stable.

**Comment by kof** [comment]
Easily reproducible on mac chrome, couldn't repro it on a blank page, here try to scroll to any text and edit it

https://webstudio-builder-fsr4449sm-webstudio-is.vercel.app/builder/3274ebde-fa97-421c-83a3-8dfafff69c53

**Comment by kof** [comment]
@TrySound I think it has been fixed in the preview
