### ISSUE TITLE
Drop the ... pending pattern in button state

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1715]
This pattern makes buttons jump around, we need a better solution

- [x] pending state hides text, shows svg
- [ ] preserves the original size with text
- [ ] loading icon is smaller than in design atm

**Comment by kof** [comment]
@markxtang lets render a spinner instead of button text when pending, I think our default cycle spinner won't look great inside a button, I would think of some animation that is more flat than a circle, e.g. animated dotts or something like this

Can you get us a nice animated SVG?

**Comment by markxtang** [comment]
![Loading Dots](https://github.com/webstudio-is/webstudio-builder/assets/122043657/aa1a65bc-f6b8-4380-8690-5043a7d4da9e)

**Comment by markxtang** [comment]
One more white version to be used on colored backgrounds

![Loading Dots White](https://github.com/webstudio-is/webstudio-builder/assets/122043657/4a6e22ce-5fe5-442c-b5a0-4997b09a73c2)

**Comment by kof** [comment]
The movement seems kinda a little choppy and slow, any way to improve it? maybe even improve the size? 9kb atm

**Comment by markxtang** [comment]
**Slow:** I exported it 1.5X faster. Let me know if it feels better
![Loading Dots V2](https://github.com/webstudio-is/webstudio-builder/assets/122043657/ab60242e-037a-441d-a935-58abcab2d634)

**Choppy:** I'm not sure what you mean, it looks perfectly smooth on my end. Here's a screen recording of what I'm seeing

https://github.com/webstudio-is/webstudio-builder/assets/122043657/c1cf9b83-7d3a-4a77-a501-74a3996e1ed8

**File Size:** This one has more animation data than the last spinner (4 transforming lines vs 1 circle). Only way I know how to drop the file size is to make a simpler animation. I'll work on some simpler options.

**Comment by kof** [comment]
Should be alright this one ... @darindimitroff do you want to take over and update design system button component pending state?

- [ ] add the svg to [ icons package](https://github.com/webstudio-is/webstudio-builder/tree/main/packages/icons)
  - please add a readme.md for how to add icons
  - add .svg to icons folder, run `pnpm generate && pnpm build` from icons package root - it will generate react components  from svgs
- [ ] render svg as an svg component inside the button

**Comment by markxtang** [comment]
Here's a white version as well for use on colored backgrounds
![Loading Dots V2 White](https://github.com/webstudio-is/webstudio-builder/assets/122043657/05570ea8-230d-408a-851a-3c1e4a66b0d8)
![Loading Dots V2 White Preview](https://github.com/webstudio-is/webstudio-builder/assets/122043657/a6343f36-a029-473d-bd3c-a0fca1521df2)

**Comment by markxtang** [comment]
Pending states for buttons have been added to the Webstudio Library Figma: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=4%3A2709&t=z7q4qJuAG7KMLSxf-1

I've also updated the loading animation SVG. Here is a preview:
![Loading Dots Preview](https://github.com/webstudio-is/webstudio-builder/assets/122043657/0f9d647c-8002-44b9-a343-a0c18722554a)

Here is the animation in 3 colors: foreground/main ; foreground/contrast ; foreground/destructive
Refer to the Figma to see which color goes on which button.
![Loading Dots Destructive](https://github.com/webstudio-is/webstudio-builder/assets/122043657/ab19b394-fef3-4f11-8a48-34c079bbf61b)
![Loading Dots V3 Main](https://github.com/webstudio-is/webstudio-builder/assets/122043657/f28ec8f1-fc8a-4dfc-8ba4-ae26359363ef)
![Loading Dots V3 Contrast](https://github.com/webstudio-is/webstudio-builder/assets/122043657/a474bbeb-9d58-4a2c-88d3-94d053e382ba)

**Comment by markxtang** [comment]
Pending animation is too small. Here it is in the [design library](https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=4%3A2709&t=mx31CQwYeHUMy1lN-1) for reference

Below: Image showing the current pending animation being too small on the button.

![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/47cda71b-6cb2-48b0-8f5d-1bc3ff8c1037)

**Comment by markxtang** [comment]
I know the SVG animation has some white space around the dots. @istarkov LMK if I should re-export without the white space

**Comment by kof** [comment]
@istarkov did you make it "preserves the original size with text" ? E.g. when text was holding the size of the button, then you render dots, do you preserve the original size of the button so it doens't jump?

**Comment by istarkov** [comment]
Yes, https://github.com/webstudio-is/webstudio-builder/blob/5cfedb69bd0964022cc8821d654fd425d90ea075/packages/design-system/src/components/button.tsx#L203
One of my favorite css feature, visibility visible child inside parent with hidden visibility is visible
