### ISSUE TITLE
Builder menu that shows logo

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1717]
People don't know they can click on the logo to get the menu. We neet to either add a chevron or make it some icon or something else?

**Comment by darindimitroff** [comment]
Spent some time looking at competitors and other apps that might share this patter in other industries.

We can visualise the problem by looking at two main tasks:
- be discoverable as a menu (key task)
- serve as a place to communicate the Webstudio brand
- blend in quietly when this menu isn't intended to be used

In my opinion, the best way to design this is to have the Webstudio logo with an arrow or chevron next to it and not dramatically change the button content on hover. This way, we have both the brand element and a constantly identifiable menu. In general, I'm not a fan of completely swapping buttons contents on hover for multiple reasons other than just accessibility.

I'll put together a proposal on Figma @taylornowotny.

**Comment by kof** [comment]
@darindimitroff I agree, the animation is too much, its distracting. Branding is also nice to keep, to give builder more personality. Chevron will fix discoverability
