### ISSUE TITLE
Tiny button component update

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1727]
The "dark" variant of the button component previously had no background specified on the default state, but it did have the "background.topbar" color token on the other states.

Now, this color is on the default state as well. That's the whole update. 

<img width="282" alt="Screenshot 2023-06-06 at 2 29 06 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/be315910-7afa-4cac-97c7-06e5d4606572">

**Comment by darindimitroff** [comment]
@taylornowotny Was the button rendering transparent in some way before or did it use a local style? Looking at the code, the dark background is already applied in the code implementation.

**Comment by taylornowotny** [comment]
Yea I suspected that might be the case even though the design said it
should be transparent. We can call this done

**Comment by darindimitroff** [comment]
In this case we can close the issue, @kof.
