### ISSUE TITLE
Style Source Badge component update

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1729]
This component is used in tooltips and also in the New Token menu.

Previously there were two variants: token and tag

Added: breakpoint and instance variants

Please check the colors as well. Those have changed and the new tokens have been pushed to github but the new colors may or may not be synced by the time you look at this issue.

This is necessary for the upcoming tooltips component update

<img width="271" alt="Screenshot 2023-06-06 at 2 38 33 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/dd1fe7f1-6ef7-43e1-be0e-40b1cfc8fec3">

<img width="577" alt="Screenshot 2023-06-06 at 2 19 38 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/46e090a3-9188-4afc-9499-e60d2dee5217">

**Comment by kof** [comment]
I think this has been done, @taylornowotny please reopen if you think its not done
