### ISSUE TITLE
Bug - pasting a webstudio URL in the gradient code input crashes the app

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1751]
Thought I had a gradient in my clipboard but it was a URL. Pasted the URL and as soon as I hit ENTER I see this screen and I'm kicked out of the builder.

Tested a few ways:
- Random text shows error state input as expected
- Pasting or typing a simple URL like apple.com or https://apple.com does not show error state input and does not crash
- Only a webstudio domain results in this behavior afaik

<img width="274" alt="Screenshot 2023-06-11 at 3 39 18 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e7eb2cb0-f305-472f-9507-d0c7902b9cc1">

**Comment by istarkov** [comment]
Can you please give URL at which you have reproduced the error and what exactly you have copypasted there as it's not reproducible

**Comment by taylornowotny** [comment]
[This is the URL of the branch that I tested](https://webstudio-builder-i1f250f9n-webstudio-is.vercel.app/) - the CSS preview branch.

Here's a video. It's a little inconsistent. Sometimes the error happens instantly on ENTER, but as you can see in the video it wasn't instant this time.
https://github.com/webstudio-is/webstudio-builder/assets/86495896/d62570f2-4df2-47ce-bd02-6a3a2703d451
