### ISSUE TITLE
Match styling of Toggle Group component with design.

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1779]
Toggle Groups and Toggle Group Buttons in the Builder are not visually consistent with the components in Figma. 

The issue might be limited to the Buttons, not sure. The Buttons at least do not have the correct styling in terms of **colors, states, borders**, or **corner radii**. 

- [ ] Match all styling of the Toggle Group and Toggle Group Buttons with the design in figma

Builder (typography section):
<img width="98" alt="Screenshot 2023-06-13 at 9 58 00 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/36bba02d-90a2-4415-b779-a754e23f3719">

Design:
<img width="138" alt="Screenshot 2023-06-13 at 10 00 43 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/56c38ef5-22da-413b-807d-425ae6b95ee3">

Component in figma:
<img width="702" alt="Screenshot 2023-06-13 at 10 00 26 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/f30dcd2a-a5a5-4d6b-945e-89b6f343a968">

Component in figma link: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=4%3A2831&t=5IvnR5mIehas70xa-1

**Comment by taylornowotny** [comment]
⚠️ Important!

The "overwritten" color has not been added to the Toggle Group Button at all, so when a value is overwritten, it shows like nothing is selected.

https://webstudio-builder-24jrt0op8-webstudio-is.vercel.app/

**Comment by TrySound** [comment]
We have inconsistent requirement. Do we need to show local/remote/overflow in toggle controls with label or not?

![image](https://github.com/webstudio-is/webstudio-builder/assets/5635476/8d551edd-f3d4-40e9-a185-432b12308371)

![image](https://github.com/webstudio-is/webstudio-builder/assets/5635476/8d72db87-0ea6-4e50-8e51-1a1be79c1b8d)

**Comment by taylornowotny** [comment]
Show color on label when there is a visible label, on the toggle group
button when there is not a label.

That work?
