### ISSUE TITLE
Height of gradient backgrounds on the body is locked at 100%

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1781]
When applying a gradient background to the body, the height of the gradient is locked at 100VH. Setting the body height >100VH and scrolling causes the gradient to repeat.

https://github.com/webstudio-is/webstudio-builder/assets/122043657/7df4c981-1eed-41c0-8c92-63859c45cfbe

Try it yourself:
https://webstudio-builder-dt2qj2ldv-webstudio-is.vercel.app/builder/93205fac-f6e8-402f-bfeb-41474644eacc?authToken=6b24bfc2-0959-42a5-a8b5-6c7fcfd6ce0e&mode=edit

**Comment by istarkov** [comment]
Until height of html element is set 100% (and we can't edit html element styles)
for some reason body can't have gradients more than html element size

**Comment by istarkov** [comment]
I'll check on modern html layouts does that possible
