### ISSUE TITLE
Use property name in background properties

### ISSUE THREAD

**Issue by TrySound** [webstudio-is/webstudio-builder#1786]
These all properties could have tooltips with descriptions and reset button

<img width="240" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5635476/c62bffc9-b229-4198-a288-1bd8189b62e2">

**Comment by ajaxbo360** [comment]
what do you mean by reset button, you mean reset properties to its original values

**Comment by ajaxbo360** [comment]
i would love to take on this issue , if no one is assigned to it

**Comment by TrySound** [comment]
Ok. Looks like reset button should not be in layers so need to add only tooltip. See property-name module. Need only tooltip with declaration description or property description.

**Comment by ajaxbo360** [comment]
can you guide me where i can find the corespondent file where i can add tooltip .

**Comment by kof** [comment]
@ajaxbo360 we need to find for something that doesn't interfere with the current work in progress that requires a lot of background knowledge on the specific task, dm me in discord
