### ISSUE TITLE
Issues with Tooltips descriptions

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1793]
I warned against using chatGPT descriptions and I am going to again request that they be removed so we can define them manually.

The descriptions are consistently unhelpful, at best just describing what is already obvious about the property from the name, with no information about how to actually use the property or value.

Here are some examples. These are the rule, not the exception:
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/9892dbac-9654-486b-8671-ff83255c665f)
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/77829ec8-ac18-4a7c-aadb-a6833ef0d709)
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/3474b08e-03c8-4250-9b4c-d33e1eaa0a9e)

We don't need tooltips that simply use the name of the property in a sentence, we need tooltips that teach users how to use these controls to achieve their vision.

We need to write these ourselves. It's work, sure, but it's less work than writing separate docs, both for us and for the user. I'd rather have no description than an AI description.

**Comment by taylornowotny** [comment]
Additionally, the descriptions on property labels seem to be descriptions of the applied value, not descriptions of the property itself.
e.g. The tooltip for the "Display" property should describe the display property - NOT the display: flex value.
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/f0b84219-4e45-49b9-8e80-dd81fee7f1ce)
It's not consistent, either. In some cases the property tooltip does describe the property even with a value selected.
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/d2a5cee2-d943-4f04-867f-24cb4ca973b7)

**Comment by taylornowotny** [comment]
Some descriptions are for the wrong property:
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/b5bb3a38-2e04-4366-992c-8a95f620636d)
![image](https://github.com/webstudio-is/webstudio-builder/assets/86495896/a5650975-77b1-4f90-92a7-b0841e065d18)

**Comment by kof** [comment]
> The descriptions are consistently unhelpful, at best just describing what is already obvious about the property from the name, with no information about how to actually use the property or value.

We can still try and tweak the prompt, I think we just didn't have time to properly tweak it and look critically at the strings

here is a complete file, please have a read, you may find more of them, then we try to tweak the prompt and regenerate 
https://github.com/webstudio-is/webstudio-builder/blob/main/packages/css-data/src/__generated__/property-value-descriptions.ts

**Comment by kof** [comment]
Lets discuss one by one what the problem is. In some cases we don't have a specific property-value combination description and we use the property description instead. I wrote this logic intentionally as a way to have a description when the combination is not available. Maybe in this case we need to adjust the prompt in a way that makes it clear.

@ggurgone please help address those issues if you think its feasible before we give up on gpt-based approach.

**Comment by taylornowotny** [comment]
This is each problem one by one:
- Descriptions as a whole are not helpful. It's a systemic issue, not limited to specific tooltips.
- Some descriptions are for the wrong property
- Some descriptions on properties are for the current value instead of the property
   - All descriptions should describe the trigger ONLY. Tooltips on properties should only describe the property, NOT the current value for that property.

**Comment by kof** [comment]
> e.g. The tooltip for the "Display" property should describe the display property - NOT the display: flex value.

We discussed it and we said that inputs don't have tooltips so we describe the property:currentValue combination as one thing in the description

**Comment by taylornowotny** [comment]
My perspective on that issue has been the same. Tooltip only describes the trigger and nothing else.

There's no need to describe a value that is already applied.

Menu options will have descriptions within the menu.

**Comment by taylornowotny** [comment]
We are currently giving users misleading or unhelpful information and that is unacceptable. We need to remove tooltip descriptions immediately and only add them in after they have been QCd and approved.

**Comment by taylornowotny** [comment]
Link to earlier notes: https://github.com/webstudio-is/webstudio-builder/pull/1746#issuecomment-1587986165

**Comment by ggurgone** [comment]
Quick reply but we can discuss more in detail tomorrow. 

The script I wrote generates descriptions for properties only and property-value pairs, so we can easily use only the properties description if we want.

As for the rest @taylornowotny since you have a better feeling of what a good description should look like, can you play a bit with ChatGPT (the free version at https://chat.openai.com) starting from the following prompt?

````markdown
Please generate a good, newbie friendly and self-explanatory description (max 140 characters) for all the CSS properties in the following list:

```
- background-color
- display
- flex-direction
- white-space
- ...
```

Respond with a matching bulleted list of the same length which contains all the descriptions as Markdown code block.

Important:

- The response list should include a description for every property in the list above.
- The descriptions should be beginner friendly and understandable by someone who doesn't know CSS.
- Don't add any other explanation.
- Don't repeat the property names in the descriptions.

Example properties list (input):

```
- background-color
- flex-direction
```

Example response:

```markdown
- Sets the background color
- Sets the flex container main axis direction
```
````

Change the wording, max length etc. and see if you can get some decent description for the properties that you list at the beginning.

If you dislike all you get from GPT (nothing wrong with that), you won't have any other option other than:

- 😩 (not ideal) write them all by hand 
- 👍 (ideal) Google a bit to see if there is an existing library or database of good descriptions

**Comment by ggurgone** [comment]
By the way I don't think we can teach people in 180 characters so in my opinion a generic explanation is enough and we can then have a learn more link pointing to each property explanation https://css-tricks.com/almanac/properties/ (this is a great resource).

Also it is worth nothing that we can still generate the property descriptions with GPT and then tweak them by hand.

**Comment by kof** [comment]
Btw maybe we should limit where gpt takes information to mdn and css-tricks or someting?

**Comment by kof** [comment]
My prompt explorations:

<details>
  <summary>
  display:  "Determines how an element is displayed on a web page, controlling its box type and layout behavior."
</summary>
  
  Please generate a good, newbie friendly and self-explanatory description (max 300 characters) for all the CSS properties in the following list only using developer.mozilla.com site

```
- display
```

Respond with a matching bulleted list of the same length which contains all the descriptions as Markdown code block.

Important:

- The response list should include a description for every property in the list above.
- The descriptions should be beginner friendly and understandable by someone who doesn't know CSS.
- Don't add any other explanation.
- Don't repeat the property names in the descriptions.

Example properties list (input):

```
- background-color
- flex-direction
```

Example response:

```markdown
- Sets the background color
- Sets the flex container main axis direction
```
</dettails>

<details>

<summary>
display - "- Controls the layout and rendering of an element on a web page, determining its box type and position in the document flow.
"
</summary>

Please generate a precise and yet easy to read description (max 60 words) for all the CSS properties in the following list only using developer.mozilla.com site

```
- display
```

Respond with a matching bulleted list of the same length which contains all the descriptions as Markdown code block.

Important:

- The response list should include a description for every property in the list above.
- The descriptions should be beginner friendly and understandable by someone who doesn't know CSS.
- Don't add any other explanation.
- Don't repeat the property names in the descriptions.

Example properties list (input):

```
- background-color
- flex-direction
```

Example response:

```markdown
- Sets the background color
- Sets the flex container main axis direction
```
</details>

**Comment by kof** [comment]
<details>

<summary>height: "Defines the vertical size of an element on a webpage."</summary>

Please generate  the most precise, extremely short and simple description (max 60 words) for all the CSS properties in the following list only using developer.mozilla.com site

```
- height
```

Respond with a matching bulleted list of the same length which contains all the descriptions as Markdown code block.

Important:

- The response list should include a description for every property in the list above.
- The descriptions should be beginner friendly and understandable by someone who doesn't know CSS.
- Don't add any other explanation.
- Don't repeat the property names in the descriptions.

Example properties list (input):

```
- background-color
- flex-direction
```

Example response:

```markdown
- Sets the background color
- Sets the flex container main axis direction
```

</details>

**Comment by kof** [comment]
Maybe when engineering the prompt, we need to think of what kind of description we want to produce in terms of how exactly it is supposed to be helpful.

E.g. "a user doesn't know CSS and yet they need to know how this property will impact the element" or something like this, trying to explain how this text is going to be used as opposed to just telling it what to generate

lets play with it a bit

**Comment by ggurgone** [comment]
Here's a potential better prompt:

````markdown
I created a no-code app for building websites. People who don't know HTML and CSS can use it to create sites easily. My app has a styles panel where the can tweak CSS properties for the selected element. Every control consists of a label and an input field. The label is the CSS property name. When the user hover over the property name we show a tooltip with information about the property.

I will now give you a list of CSS properties and I want you to generate a matching list of explanations that are no longer than 180 characters and teach the user what is the property about! I looked at  https://css-tricks.com/almanac/properties/ and their explanations seem very good!

Here is the list of CSS properties:

```
- display
- height
- appearance
- flex-wrap
- flex-direction
- flex
- justify-content
- z-index
- white-space
```

Respond with a matching list of explanations. 

If the explanation includes some but not all the possible values for the property say "and more" at the end. Keep in mind though that it is not necessary to add values examples to every explanation.

Don't include the property name in the explanation.

```markdown
````

And here is the answer: 

```
- Controls how an element is displayed (block, inline, etc.).
- Specifies the height of an element.
- Changes the appearance of certain elements (buttons, checkboxes, etc.).
- Determines whether flex items should wrap or stay on a single line.
- Defines the direction of flex items in a flex container (row, column, etc.).
- Sets the flexibility of flex items in a flex container.
- Aligns flex items along the main axis of a flex container (start, end, center, etc.).
- Sets the stack order of positioned elements.
- Specifies how white space inside an element is handled (normal, pre, etc.) and more.
```

Looks pretty good in my opinion.

**Comment by kof** [comment]
@ggurgone its pretty good, I can see how Taylor may say this is still not good enough overall, but it's definitely a good start and maybe if Taylor can express what exactly he wants it to change and plays with the prompt himself, we could improve.


If he is still not happy, we can start overwriting with manual definitions things that are most important and very visible and go with a mixed approach, while still having a clear description for 347 properties and 2582 property:value declarations

In particular for declarations it would be nearly impossible to write them manually, even if we reduce the list to those we actually show in visual style panel

**Comment by kof** [comment]
It's very doable to have manual descriptions for the properties only we have in the style panel, it won't be hundreds

**Comment by ggurgone** [comment]
> 2582 property:value declarations

to clarify, you also want these? At some point in this conversation I thought you didn't. Quoting Taylor:

> Additionally, the descriptions on property labels seem to be descriptions of the applied value, not descriptions of the property itself.

> Some descriptions on properties are for the current value instead of the property. All descriptions should describe the trigger ONLY

> Tooltip only describes the trigger and nothing else. There's no need to describe a value that is already applied.

**Comment by kof** [comment]
From my understanding we still need both, the only change is that we only show property descriptions on property and we show property:value descriptions on values

**Comment by kof** [comment]
btw @taylornowotny @ggurgone we could probably increase the precision of text by giving it a higher characters limit, @taylornowotny what's the max amount of charaters you want to see in the tooltip? Do you potentially want to shorten the text with ellipsis and let user click more directly in the tooltip?

**Comment by ggurgone** [comment]
I am fine either way, you and Taylor though should agree on the final approach to take. 

I can only suggest that we generate with GPT regardless and then Taylor can review these and do tweaks. Alternatively if Taylor is willing to compile a smaller list of properties we can use that instead of [the full MDN one](https://github.com/webstudio-is/webstudio-builder/blob/main/packages/css-data/src/__generated__/keyword-values.ts).

**Comment by taylornowotny** [comment]
Regarding length, 140 characters will result in 4 lines of text for the description. That's a reasonable limit considering we have to balance the clarity of the description with the size of the tooltips, which are loaded with other things. No I do not want to use a "read more" pattern. The MDN link is for users who want more.

140 is a soft limit, not a target though. Ideally the description would be as short as reasonably possible. I'm not sure how to put that into a prompt, I'll leave that to you @ggurgone , but it wouldn't be right if every description was 140 characters.

**Comment by taylornowotny** [comment]
The latest prompt is a small improvement but it's not there yet. Most of the descriptions are still just using the name in a sentence.

What needs to change?
The fundamental purpose of tooltip descriptions is to teach users how to use a part of the UI to accomplish their intentions. 

**Bad example from the above results:** white-space - says "Controls the white space of an element"
- That's frustratingly useless.

**Good example:** appearance - "Controls the visual appearance of checkboxes, radio buttons, and other form controls."
- That's better becuase it includes more information than is obvious from the property name alone.

**Bad example #2:** flex-wrap - "Determines how flex items are laid out in multiple lines."
- How does it determine that? This description gives me no information about how to use flex-wrap in a website.
- My description: "Controls how flex items wrap (break to the next line) if it overflows the container."
    - This explains what wrapping is, when wrapping normally occurs, and what is being wrapped. I expect a new user with no CSS experience will be able to use this property effectively based on this description.

Will this help you improve the prompt @ggurgone ?

**Comment by taylornowotny** [comment]
My expectation for these generated descriptions is that they be more informative than simply restating the name of the property.

From that point we can efficiently make manual adjustments to add helpful details, Webstudio-specific advice, and human language on a case-by-case basis. But obviously we want to reduce the extent to which this is necessary.

**Comment by ggurgone** [comment]
Those are super valid points, will should try to add restrictions to the prompt perhaps with examples of good and bad descriptions. 

>  I'm not sure how to put that into a prompt

You can just edit the prompt, it is just text. There is no magic, you just try to write a prompt message like [this one](https://github.com/webstudio-is/webstudio-builder/issues/1793#issuecomment-1592542993) and see what GPT responds. You don't like it edit the prompt and ask again.  

@taylornowotny can you play with the prompt on https://chat.openai.com tweaking [this prompt](https://github.com/webstudio-is/webstudio-builder/issues/1793#issuecomment-1592542993) until you get results that you think are good enough? Doing this back and forth where I try one prompt, post it here, wait hours for feedback and repeat is slow and not ideal.

**Comment by taylornowotny** [comment]
Good idea and I will get involved with the prompt next week when I return from a brief trip to see family.

In the mean time you can try and improve the prompt based on the goals and expectations that I described above. I think I was pretty clear and thorough. You should be able to evaluate for yourself whether a description is helpful or not.

**Comment by kof** [comment]
@TrySound lets update the descriptions using this prompt and then once we update it again once we have a better version

https://github.com/webstudio-is/webstudio-builder/issues/1793#issuecomment-1592542993

**Comment by ggurgone** [comment]
@taylornowotny sorry I didn't know you are on a trip.

@kof I can run the script now if you want

**Comment by kof** [comment]
@ggurgone yes please!
