### ISSUE TITLE
Add a "Clear Styles" option to Local Styles

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1799]
Add a "Clear Styles" option to Local Styles to allow users to remove all styles and reset Local Styles to default. Include a confirmation dialog to avoid users from losing work due to accidental misclicks.

Relevant part of the [Docs Figma](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1014%3A31742&t=ZZeyH6CuQz1q3bhR-1)

![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/8f93c30d-6ada-42ca-936f-69a80bfd3e36)

**Comment by kof** [comment]
Do we really need a confirmation dialog? since it only affects the local styles, current token and can be undone with undo-redo, I don't see a strong need

**Comment by markxtang** [comment]
I'm leaning towards not needing a confirmation dialog. @taylornowotny any thoughts?

**Comment by taylornowotny** [comment]
Needs confirmation to prevent losing work due to accidental click.

**Comment by kof** [comment]
@taylornowotny but there is still undo/redo functionality! We added confirmation for "delete" because it impacts other instances and so user may not realize what this will do and confuse it with "remove". But in this case I see no need

**Comment by taylornowotny** [comment]
Ok we can always add it later if needed. No dialog for now.
