### ISSUE TITLE
Form method and action are not configurable; sends pre-defined email directly to account's email

### ISSUE THREAD

**Issue by BrockMcKean** [webstudio-is/webstudio-builder#1806]
Form properties `method` and `action` are not available in the properties panel.

All form submissions send to the WebStudio user's registered email address from a webstudio.email address that seems to be generated corresponding to the Page

WebFlow exposes `method` and `action` so it seems like a fair requirement to at least keep parity with their functionality on forms given how important they are. Also, perhaps a major selling point if the submissions allotments are greater/unmetered.

Marketers and low/no-coders will hard require these settings be exposed as they will have existing crm/smtp providers and not be easily willing to switch. Might get away with integrations + key setting for most popular.

Devs will also require configuration of the form submission event/data. A webhook setting if nothing else.

**Comment by kof** [comment]
I agree with this, I failed to notice that we removed them as we were building a default submission mechanism  by email, which is probably a great option for small sites who don't need CRM and other things.
