### ISSUE TITLE
Preview links don't show preview mode on the 

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1841]
Steps to reproduce:

1. Follow this link:
https://apps.webstudio.is/builder/fb4ef6b3-7887-43fd-b3c1-6ff33700d552?authToken=166397ab-0f49-4eab-aa5c-3f4b752b4326&mode=preview

2. It should open in preview mode, but the preview button will be in the "off" state.

3. Clicking the preview button turns off preview mode, but turns the button to the "on" state. This is backwards. The "on" state of the button should show when in preview mode only.

Toolbar Toggle Button component: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=1512%3A7422&t=N1E9gl5gEc6NOqP1-1

**Comment by kof** [comment]
@istarkov looks like preview mode button state management is just using exact opposite value for on/off when coming from that link
