### ISSUE TITLE
Option+click on labels does not reset properties

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1844]
It's working in some places but not others.

option+click works for:
- space section
- icon button
- toggle button
- nested icon labels

option+click does not work for:
- [ ] property labels
- [ ] toggle group buttons
      (opt+click on a 'local' or 'overwritten' value should remove the style definition from the token.)
- [ ] section titles used as property labels (backgrounds)

**Comment by kof** [comment]
Confirmed, broken in production, worked before
