### ISSUE TITLE
Default font size and height is different from the design

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1845]
The design specifies that the default value font-size is 16px and line-height is 1.2- 
<img width="345" alt="Screenshot 2023-06-23 at 12 02 30 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/95d73ab2-6979-49eb-b6fc-ac29e0677d07">

Is there a specific reason that the builder is not following these defaults or have they just not been implemented yet?

**Comment by kof** [comment]
Is this about inputs or labels?

**Comment by taylornowotny** [comment]
> s about inputs or labels?

Neither - it's about the default values for new Webstudio projects

**Comment by kof** [comment]
@taylornowotny got it

@TrySound we are setting font size and line height and font family on the body component but seems like we should not just move them to normalize body and adjust the values according taylor's proposal, wdyt?
