### ISSUE TITLE
Style source info for inherited styles is missing

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1895]
- [ ] The font and height properties have an orange label with no Value source in the tooltip. Orange labels represent remote user-added values so they should always show the value source in the tooltip. But these orange labels show on a new project with no user styles. These properties should be gray labels (Webstudio default) instead.

<img width="247" alt="Screenshot 2023-07-03 at 9 07 06 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/f05796bf-aad9-418d-8ed6-3d2eb4c1421e">
<img width="314" alt="Screenshot 2023-07-03 at 9 09 44 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e2f80c69-84f9-45db-ae8d-3ad0bd2e198c">

- [ ] Why do we have a text element nested inside the heading? I would expect that the headings can not be containers.

<img width="245" alt="Screenshot 2023-07-03 at 9 10 34 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/7b5f5bb4-28ed-4787-b34c-1d59a3a9572a">

_Originally posted by @taylornowotny in https://github.com/webstudio-is/webstudio-builder/issues/1888#issuecomment-1618800124_

**Comment by TrySound** [comment]
1. They are inherited

**Comment by TrySound** [comment]
2. Of course they can
