### ISSUE TITLE
Settings Panel design update and new sections

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1905]
Related to #1880 

The Settings Panel design and docs have been updated. [See Figma docs.](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1932-46522&mode=design)

The new sections and order is:
1. Generic settings. These are not inside a section. Includes stuff that is on every component like Name.
2. States (hidden when it has no contents)
3. Properties
4. Attributes

To do:
- [x] "Custom Properties" and "Properties" are now one section. Webstudio default properties can not be removed.
- [x] change "Instance Name" to just "Name"
- [x] "Name" layout changed to horizontal with 144px width input
- [x] "ID" input changed to match generic string controls and put inside of Properties section
- [x] "Custom Attributes" is now just "Attributes"
- [x] Add new "States" section
- [x] change New Property combo box placeholder text to say "New Property"
- [x] new properties are added at the top of the properties list so the user doesn't have to scroll to see the new property combo box
- [x] update the spacing and gaps as described in the Anatomy section of the docs
- [x] make sure there is 16px padding at the end of each section that has a section title (currently it is 8px)

**Comment by kof** [comment]
@taylornowotny I realized that if we add properties on top, they will be above the non-deleatable propererties ... did you expect that?

**Comment by taylornowotny** [comment]
Of course that's the intention of the design. The idea is that if a user adds a property, they will want to start configuring it right away so we don't want to make them scroll or force scroll in case there are already a lot of properties. Plus the proximity of the + and - buttons, without being separated by the non-deletable properties, makes a pattern that makes their function intuitive.
