### ISSUE TITLE
Update the Publish window to make the "name" field bigger

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1906]
![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/d7f74d40-52e8-46dd-ad66-91824363e5b4)

See Figma docs for specifications: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6120%3A54428&mode=design&t=OSNAkrzSGitzcfRa-1

**Comment by taylornowotny** [comment]
- [ ] Also, the new domain input now starts with "www." in response to feedback becuase the www. is sometimes necessary to include

<img width="461" alt="Screenshot 2023-07-05 at 3 18 16 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/a97687f1-9bd3-4877-8685-2db99d7f71da">

**Comment by kof** [comment]
Regarding www. this is an old thing people used to do a lot, we shouldn't encourage this. The problem lies with some outdated registrars, its not the default
