### ISSUE TITLE
Default styles should have a gray preset label

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1910]
I know previously we have said that only defaults coming from Webstudio should have gray labels and not CSS defaults. The headings issue requires changing this.

The margins, font-weight, and font-size of headings have a default value that most users will want to change. The lack of a label on these properties makes them hard to find.

<img width="246" alt="Screenshot 2023-07-07 at 12 14 32 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/25c8a335-dd6e-43df-8176-700ce634e1fb">

I have updated [the docs in Figma](https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=4804%3A52281&mode=design&t=5wgCV8oOyBlKcVr0-1) as follows:
> When a value is set by default, we use the preset color.
> - Do not use this label for global CSS defaults, like width: auto or background-color: transparent or display: block.
> - Do use this label for element-specific CSS defaults, like the vertical margins on a Heading element.
> - Do use this label for Webstudio component defaults, like font-family: Arial on the body element or any default component styles that are not defined on a token.

Does this updated guidance make sense? Any suggestions?

- [ ] Add gray preset labels to headings properties with default values: margins, font-weight, and font-size

**Comment by TrySound** [comment]
> Do not use this label for global CSS defaults, like width: auto or background-color: transparent or display: block.

All you described is global css defaults. So the issue contradicts itself.

**Comment by taylornowotny** [comment]
You understand the UX problem that we are trying to solve, right @TrySound?

If the terminology I used was not ideal then please suggest a better alternative.

**Comment by taylornowotny** [comment]
If the terminology I used was not ideal then please suggest a better alternative.

**Comment by taylornowotny** [comment]
Updated guidance:

We use preset labels for important default values. The design docs will always specify which properties should have preset labels.
- Do not use this label for typical CSS defaults that are the same on most elements, like margin: 0 or width: auto  or display: block.
- Do use this label when a specific element uses a different default value from the typical default, like the vertical margins on a Heading element.
- Do use this label for Webstudio component defaults, like font-family: Arial on the body element or any default component styles that are not defined on a token.

Thoughts? There is no technical logic behind the preset labels but the UX logic seems clear to me

**Comment by kof** [comment]
@taylornowotny we differentiate between browser defaults and presets. Later is what webstudio set that is different to browser defaults. If you see values that have no label - these are defined by the browser, which is why we don't have a label on them.

**Comment by kof** [comment]
In other words not everything that has a value is a preset.

**Comment by taylornowotny** [comment]
@kof I'm aware that's how it works currently. I am suggesting we change that for the reasons described in this issue. Design will always specify which properties need the preset label. There's not too many that this would be a problem.

**Comment by kof** [comment]
Arbitrary placing preset label is not an option. Either the value comes
from preset or it isn't. @trysound correct me if I'm wrong

**Comment by taylornowotny** [comment]
Not arbitrary, just not automatic. The design will specify and follow the
UX pattern described. This isn't much work. Why are you saying it's not an
option?

**Comment by kof** [comment]
Because labeling is bound to the logic of where the value actually comes
from. It's not custom made rendering case by case.

To get the gray label, value needs to actually  come from a preset.

It's data driven.

We can put that value in a preset, but the best way to do it is on tag
style source so we don't break existing sites which has been built with the
browser defaults.
