### ISSUE TITLE
Headings have a text element nested inside - odd behavior

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1912]
Currently headings have a text element nested inside with some very unusual behavior:
- you can nest elements inside headings
- the nested text element doesn't show until you nest something else inside the heading, then it's visible
- no drop down arrow on the heading until you nest something else inside

Suggested fix:
- [ ] Headings should not allow nesting. This should be impossible unless there is a specific use case for it.
- [ ] Headings should represent a h1-h6 element, not be a container for a text element

**Comment by taylornowotny** [comment]
https://github.com/webstudio-is/webstudio-builder/assets/86495896/d95db524-0137-47fd-a414-7712a7f887da

**Comment by kof** [comment]
This is the general behavior we have for things that can be text-only or accept child instances. Technically it is allowed to have children in Headings and shouldn't be disallowed artificially.

So what's the problem with the current behavior exactly except that webflow doesn't support this?

**Comment by taylornowotny** [comment]
Problems with the current behavior:
- It's inconsistent and confusing to have a nested item that is only revealed when another item is deliberately nested with it
- Headings are an HTML element. They are not a text element in HTML so what's the sense in nesting a text element inside the heading?
- In principle all user interfaces limit what is possible for the user according to the intentions of the design. If there is no use-case for nesting things inside headings, then headings should not allow nesting. Why would we allow users to do something that doesn't benefit them in any way rather than preventing it? Just copying code behavior? This is just as reasonable as copying Webflow.

**Comment by kof** [comment]
Most html elements can contain text without other elements, so does heading
by default unless you place an element inside. When you do, we have to put
the text node that was there before inside a Text component.

Afaik it's Lexical editor limitation @trysound


As soon as you select text inside heading and make it a link or cursive,
this will be also nesting.

There are tons of other use cases, e.g. placing an icon

**Comment by taylornowotny** [comment]
Alright if you're saying there's a technical benefit to it being this way then I can't argue.

All I can say is that the UX of this component is not good. As a vis dev, I want it to work like Webflow.

**Comment by kof** [comment]
I don't understand the problem you mentioned initially.

Maybe record a video to make it clear?

**Comment by TrySound** [comment]
> It's inconsistent and confusing to have a nested item that is only revealed when another item is deliberately nested with it

See we cannot edit text when non-textual instances are dropped into text container due to technical limitation of our editor (we will try to beat it in the future).

So it's not revealed. We wrap the text and textual elements (Bold, Italic) with Text component to keep it editable while still allowing to add anything inside text containers.

This also means you can edit Box as text when it does not have anything non-textual inside.

**Comment by kof** [comment]
This logic is what allowed us to get rid of things like Link block and link
text and just have a Link.

Same for multiple otherncases
