### ISSUE TITLE
Settings Panel: The text input field next to the label "name" is too long. It's making the label truncated.

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1960]
Here's what it looks like:
![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/03f5afce-02a8-4203-b00b-13e5306041c7)

Here's what it looks like in the Design Docs
![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/75a48100-ef7a-4fbc-8a99-16764334168f)

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=1932-46522&mode=design&t=41joLRiWq8NyDDev-0

**Comment by kof** [comment]
<img width="251" alt="Screenshot 2023-07-20 at 01 51 38" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/6468d152-2b1d-4c55-b95f-95b85a6ca3d7">


its a second report of this, one is in bugs from community on discord, also on windows, @istarkov any idea?
