### ISSUE TITLE
Prevent users from using unsupported browser

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#198]
It can be frustrating if user thinks we support the browser just because it looks ok on the surface. Since we are not testing anything  but chrome for the Beta release, we should have an overlay with explanation in all other browsers to prevent frustration.

**Comment by SaraVieira** [comment]
What do we need to support in order for the website to work?

**Comment by kof** [comment]
I think we should enable chrome only for now. Just to avoid negative impressions from browsers we didn't test in.

**Comment by kof** [comment]
We can do this right after we have the dialog https://github.com/webstudio-is/webstudio-designer/issues/831

**Comment by kof** [comment]
@taylornowotny can you please make a low-effort for how toshow a simple message in the middle of the screen  says something like:

"Hey there! At the moment, we only support Chrome. But don't worry, we're working on expanding to other browsers soon."


Ideally we would use an overlay with modal and darken background.

**Comment by taylornowotny** [comment]
Is this a notification that can be dismissed or are we forcing users to use a chrome-based browser?

**Comment by kof** [comment]
Lets make it dismissable but it would come back after reload, so not persistent

**Comment by kof** [comment]
Depends on https://github.com/webstudio-is/webstudio-designer/issues/899

**Comment by kof** [comment]
We have a bunch of bugs in safari including layout bugs 
![image](https://user-images.githubusercontent.com/52824/219022720-7fde3e08-c57f-4e73-bae5-067c40e51e65.png)

I think we should literally disable all other browsers with an overlay. I don't want to deal with frustration and bug reports in those browsers.
