### ISSUE TITLE
Smart Quotes don't work

### ISSUE THREAD

**Issue by markxtang** [webstudio-is/webstudio-builder#1989]
When typing in the Builder, quotation marks are always straight, regardless of whether they are before or behind a word. 

This is a good article that explains quotation marks in more depth: https://practicaltypography.com/straight-and-curly-quotes.html

https://github.com/webstudio-is/webstudio-builder/assets/122043657/797e1987-a87d-4649-bfa5-885f992e29f9

**Comment by TrySound** [comment]
We put what the actual character is encoded in keyboard. Figma seems replace it with unicode characters implicitly. I would not call it a bug. You can write in GitHub issues and see same behavior we have.

**Comment by markxtang** [comment]
@TrySound Understood, I relabeled the issue as an "enhancement" instead of a "bug" I still feel it's important to implement. Here's why (quoted from the article I shared):

![image](https://github.com/webstudio-is/webstudio-builder/assets/122043657/695a3527-adbe-4169-a2a8-56c46eb68810)

**Comment by kof** [comment]
should we close thise one as wontfix?
