### ISSUE TITLE
Duplicated items should be parallel to the original, not nested inside.

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1994]
We want this behavior to be consistent with user expectations. Both Figma and Webflow use the intended behavior as exemplified below.

Figma:
https://github.com/webstudio-is/webstudio-builder/assets/86495896/9645bb85-cfe5-41eb-9c8c-e3cf1dd57e5c

Webflow: 
https://github.com/webstudio-is/webstudio-builder/assets/86495896/b08403cc-e344-4300-b83b-7f7bfabeefe6

- [ ] When pasting or duplicating an instance, the position of the new instance should be parallel, and below, the copied instance. It should not nest the new instance inside the copied instance.
    Open parents can be closed when duplicated, for space efficiency. See example from Webflow.

The current behavior has three major problems:
1. When duplicating, the nesting is not the expected behavior. We should be consistent with Webflow and Figma patterns.
2. This is not the most commonly desired behavior so it creates a slowdown. The user must spend time opening the original, then dragging the duplicate out of the original to place it in the intended position, which is probably in parallel with the original. 
3. The nested duplicate is not immediately visible in the Navigator because it is nested.

**Comment by kof** [comment]
The problem here is that we are missing this check: if the selected instance id is the same as the one we copied - its a duplication, insert after it, otherwise insert inside it
