### ISSUE TITLE
Add tooltips for component properties in Settings tab

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#2027]
These tooltips will only be a Title and Description - no Value source section, no CSS code.

We should generate the content via Ai like the other tooltips. The content of the tooltips is intended to help the user understand how to use the property. Please coordinate with @ggurgone

**Comment by kof** [comment]
@istarkov lets add tooltips
@ggurgone will generate descriptions like we did for css properties once he is back, before the launch

**Comment by TrySound** [comment]
But props come from components. Components may have own meaning for native props or add new ones.

**Comment by taylornowotny** [comment]
What do you suggest as a solution to that @TrySound ?

**Comment by kof** [comment]
We generate descriptions for html attributes only, custom once will be
defined manually from meta

**Comment by ggurgone** [comment]
Hey there, is this something that you need now? Should I start today?

**Comment by kof** [comment]
Yes, we really need descriptions for all html standard attributes! to show them next to properties

**Comment by kof** [comment]
@taylornowotny is there supposed to be a tooltip on hover of the property name? or an icon like for bound properties?

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6762-53564&mode=design&t=7tCNGjEaXxqBVI19-0

Because if its supposed to use the icon and icon is literally next to every property, will this look good?

**Comment by ggurgone** [comment]
I will look around but do you know if there is a db with standard description for html attributes? Perhaps from MDN?

**Comment by taylornowotny** [comment]
@kof Tooltip over the name, just like CSS properties in the Style panel. Icons in the label are only for special cases, like explaining to the user why a disabled property is bound. The label and the icon would have separate tooltips when both are present. 

@ggurgone That looks good to me! Yes, the title is supposed to be attribute/property name. This is useful for displaying the entire name in case it is truncated in the UI.

**Comment by taylornowotny** [comment]
closed via #2125
