### ISSUE TITLE
Add Radix Switch component inside the Form section

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#2031]
We need a Switch component from Radix.

The Switch and the Select components should both be listed within the Form section in the Components tab, not in the Radix section. The user must nest these components inside a Form to use them properly so it's more intuitive to group them with the other Form elements.

**Comment by TrySound** [comment]
What is the point of radix section if we not list all radix components there?

**Comment by taylornowotny** [comment]
The point of the Radix section is to group the components that have special interactivity beyond the standard components. We might rename this section to 'Advanced Components' or something. It will include components that are not from Radix. 

The point of the Form section is to group all components that must be used within a form. This is a critical point of communication with the user of how to use to these components. Doing otherwise is setting our users up for confusion.

Furthermore, the Switch and Select components are not specific to Radix. We don't need to use Radix for these at all, but we are doing so as a shortcut to making them from scratch. In other words it's not special that they come from Radix, but it is special that they belong inside of a Form.

**Comment by kof** [comment]
We need to think this through.

Radix UI over time will move into marketplace and user will install it.

It would be impossible to move it once it's inside of various sections,
because people don't know it's radix.

Beyond that knowing it's a complex library component and not native select
is important for various reasons. I wouldn't want to just mix them within
primitives.

**Comment by gopalg262000** [comment]
How can i use the switch component inside the radix form control?

when i try that below error occurs
`Uncaught TypeError: control.setCustomValidity is not a function`

**Comment by kof** [comment]
@gopalg262000 please create a separate issue with full steps to reproduce, maybe ideally with a video. I just added it and saw no error.
