### ISSUE TITLE
Webstudio Custom Code Video Review

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio-builder#2032]
First draft of custom code video recorded. 

- Are there changes that are required that can be made in post? 
- Are there changed that are required that will need a full re-record? 

Video url: https://drive.google.com/file/d/13EjUIVZnUTvjJJh2DvNEzFJwUDgWKQLd/view?usp=sharing

**Comment by kof** [comment]
We can't record it with this bug https://github.com/webstudio-is/webstudio-builder/issues/2104
