### ISSUE TITLE
Update Radix icons to use 16px icons instead of 22px

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#2040]
(updated)

I thought we were able to use 22px icons for the Components panel and 16px versions but apparently this is not the case.

Our icons are inconsistent now. Some are using a scaled-down 22px icon and others are using a scaled-up 16px icon.

Moving forward we will only have one set of icons (16px). I have removed our 22px icon set.

- [ ] Please update all Radix components to use 16px icons instead of 22px icons.All other components are correct - only Radix needs to be updated. 
NOTE: This includes the icons for children of Radix components, like the Trigger icon!

Sorry for any confusion.

**Comment by taylornowotny** [comment]
Example: I can tell that this icon is a scaled down 22px icon becuase the view box is 22 x 22.

<img width="802" alt="Screenshot 2023-08-04 at 11 19 29 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/cf675f30-d706-403b-ae03-4ab94638885e">

**Comment by istarkov** [comment]
Please give exact link as I copied icons from the discord thread link. Im pretty sure I did no mistakes in copying them.

**Comment by taylornowotny** [comment]
You didn't make any mistakes you were just given the wrong instructions becuase there was a misunderstanding on my part.

https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=4435%3A10179&mode=design&t=pH8kLKfAR6UBNwLs-1
