### ISSUE TITLE
Change Sign in spelling on homepage to have a lowercase "I" 

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2044]
The Sign in tab inside homepage navbar has a typo.

![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/9cbbdcde-450a-4e3c-82c5-41d7f97033e1)

Needs to be changed from "Sign In" to "Sign in"

**Comment by kof** [comment]
Feel free to change it
