### ISSUE TITLE
Incomplete Property name  in Text Input Component

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2045]
In the Text Input Settings, the Auto Focus property label does not dsiplay completely.. 

Attaching screenshot for reference:
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/0306a20b-7664-4615-a828-cda7452df7e6)

**Comment by kof** [comment]
fixed https://github.com/webstudio-is/webstudio-builder/pull/2037
