### ISSUE TITLE
Confusing text in all Radix Components' Properties

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2046]
I cant understand what "Is Open" means and I am sure this is a typo/bug of sorts. Doesn't even change if I select "Initial" or "Closed" instead of Open.

![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/f300c55e-fd78-4cbe-ace7-1136a52224b7)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/133adfff-f95c-4989-bb04-396dd90fd92f)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/94fe9aab-139a-4ac2-a48e-d4dc48526f99)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/66d70c4d-b05d-4a86-89b4-9da2125c0f96)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/41070733-b9f2-41a1-9141-061eed91d7e1)

Please elaborate/fix.

**Comment by kof** [comment]
Yeah, this is still in prototyping stage and will not stay as it is now. Radix components are not released.
