### ISSUE TITLE
PRE-Recording Video Review - Link Component

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio-builder#2056]
Overview of what will be in the link component: 

https://www.berrycast.com/conversations/430803e5-fca2-5923-a3b3-77f77ca81916

**Comment by kof** [comment]
I think its also a good idea to always read a few articles, starting with mdn https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

They will add some important nuances to the content.

One thing that is frequently misunderstood: whats the difference between a link and a button. For example webflow has a Button component that is actually a link. This is a major sin. Link should be always used and called a link when it leads to a different document or portion of the same document. It is literally containing the link that is a global ressource identifier, meaning across the globe this link will always lead to the same place.

Links often styled like a button but that doesn't make them a button, they are still a link. Sometimes we refer them as to link-button.

A button on the other hand can be used to submit form data or to do any javascript-based handling, but it doesn't lead you to a ressource.

**Comment by kof** [comment]
Another point is that link has a bunch of pseudo classes / pseudo states that are specific to the link and user should know the difference between them

**Comment by itsNintu** [comment]
First cut of the link component is finished. 

Changes I will make: 
- Under the style section, the editor cut out the section about "visited, Active page". 

Questions: 
- For the 30s I talk about the link component, it's on a dark background (with dark blue text). I don't show anything with it while it's in the dark state so should not impact the user, but not very visible. Do we need to re-record this portion?

@kof Let me know if there is anything outside of the changes you would like included, and if we should redo the 30s on dark background.
