### ISSUE TITLE
Design Tokens for variants api

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#2137]
## User Story

- As a user I want to be able to style component variants. 
- As a user, I want to see all component variants in the style sources autocomplete list
- As a component author I want to declare what variants my component has.
- As a user I want to be able to combine each variant with each possible state. 
- As a user I want to see all variants in style panel without switching to settings panel

Example Button style sources: `[Local, Base, Ghost, LG]`. This is a button that has a base styles token as well as variant and size tokens applied.

## Todo before launch
1. We remove style variants from props 
2. Delete token will only delete the token created from component token template, it won't delete the original token from token autocomplete
3. Token label will be e.g. Destructive
4. We add scoped tokens defined in meta, they act just like a template, once added, we create a scoped token

## Todo after launch
1. scoped token is only visible for particular component
2. Token has a variant name. When user adds variant A and then searches for tokens, A variants will have a red warning icon, because multiple variants shouldn't be used together. We still will allow it.
3. Instead of "Existing Tokens" in autocomplete we get: "Global Tokens" and "Component Tokens"

**Comment by taylornowotny** [comment]
This issue can be resolved with no effort at all by simply removing variants from components. They don't help the user in any way. Any engineered solution for variants with probably conflict with the variants UI that will be deliberately and holistically designed as part of the user-made components feature. More detail -> https://discord.com/channels/955905230107738152/1141720265978548234/1142152305580457984

Please just remove variants from all components that have them.
