### ISSUE TITLE
Text Area Component named differently in Forms and Radix sections

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2165]
See this (Forms)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/738fa933-4ecd-47c5-9c75-dc0d37d7ffac)

and this (Radix)
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/906cd713-a01a-484a-b562-206ba5a277db)

I believe this needs to be corrected

**Comment by kof** [comment]
We just had a meeting and decided to remove all components from radix that don't have extended functionality and only added for styles there
