### ISSUE TITLE
Token dropdown chevron is wrong color

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#2204]
Current preview:
<img width="54" alt="Screenshot 2023-08-28 at 10 04 37 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8b3f47fc-9418-43ea-add0-8a19f376b6d3">
<img width="142" alt="Screenshot 2023-08-28 at 10 04 27 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/52365415-fb1d-4000-96a4-213c34277a74">

Design - arrow is foreground.contrast.main token:
<img width="123" alt="Screenshot 2023-08-28 at 10 05 40 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/e4dd5da5-7556-4f4f-beb7-cef1b1216bd3">
https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=947%3A3697&mode=design&t=pXYfgfstmONNsPXb-1

In addition to the chevron being the wrong color, the "open" state of the Style Source is not matching the design. The "select menu trigger" should have token: background.button.hover when the trigger is hovered or the menu is open. See the design for details.

**Comment by TrySound** [comment]
Icon color is fixed already. On prod since yesterday.

**Comment by taylornowotny** [comment]
> Icon color is fixed already. On prod since yesterday.

Nice thanks! I will close this becuase there is another issue for the open state already i think
