### ISSUE TITLE
Add an ability to edit labels in the navigator tree

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#222]
Users should be able to edit labels of components in the navigator tree.

(SEE 6/28 UPDATE BELOW)

**Comment by kof** [comment]
Enter key should probably enable editing too

**Comment by kof** [comment]
@taylornowotny can we start private beta without this feature? I am not sure

**Comment by taylornowotny** [comment]
We could do without this for private beta, but it's a pretty important feature for one big reason. We don't name layers/elements automatically. Webflow names elements according to their class name, which isn't appropriate for us with tokens. So the only way to identify elements in the Navigator is to re-name them.

Imagine managing a serious build where all the sections are named "Block" and there are dozens of nested elements named "Block" and the only way to distinguish them is by their appearance on the canvas or the differences in the style panel.

So re-naming is a pretty big deal, but it's still possible to make a site without it. If this isn't an especially challenging feature to build I would say let's include it in the beta.

**Comment by taylornowotny** [comment]
Enter key should probably enable editing too

I assume you mean pressing ENTER while an element is selected will enable editing. This will not be ideal becuase the element is selected in the Navigator when the user is working on that element, editing styles and everything else. The user might use ENTER to deselect an input field or something and inadvertently begin editing the name of the element, at which point they could inadvertently delete the name by pressing some other key.

**Comment by kof** [comment]
Enter would only work if user focused the element in the tree specifically, not from canvas

**Comment by taylornowotny** [comment]
I'm not sure why there's a difference. Selecting from navigator vs canvas
should have the same effect.

But if you're saying that as soon as the user moves focus away from the nav
item, then ENTER will *not* start editing the name, then that works just
fine. I only want to avoid a situation where a user is pressing ENTER while
working with the style panel and starts editing the nav item name
unintentionally.

**Comment by taylornowotny** [comment]
UPDATE:

Naming your instances is an essential way to keep a project organized. Currently it's only possible to change the instance name in the Settings panel but there needs to be a faster, easier way.

Design:
Screenshot 2023-06-28 at 10 29 56 AM
https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=8%3A1872&mode=design&t=vbowmO17y48m75hM-1

- [ ] A double-click on the text area of the Navigator Item should initiate editing. (Reference Figma Layers for ideal behavior).

- [ ] Enter or loss of focus should hide edit interface and save the value

❌ Enter should not initiate editing. 

- [ ] The new label should appear everywhere. For example, in outlines on canvas

- [ ] We also need a keyboard shortcut for changing the instance name of the current selection. In Figma it's CMD/CTRL+R Does that work for us? @kof

**Comment by JayaKrishnaNamburu** [comment]
Hey i am going to work on this, thanks for the details. Once kof also gives a go on the changes. I will start the implementation 👍

**Comment by kof** [comment]
@JayaKrishnaNamburu definitely ago, it's a long-standing issue!

**Comment by taylornowotny** [comment]
@JayaKrishnaNamburu Thank you for your help and let me know if you have any questions!

@kof Are we good to use `CMD/CTRL+R` to rename the current instance?

**Comment by kof** [comment]
> @kof Are we good to use CMD/CTRL+R to rename the current instance?

@taylornowotny seems its the shortcut in figma, wf doesn't have one so yea cmd+r on mac, ctrl+3 on win

**Comment by kof** [comment]
@taylornowotny typo
