### ISSUE TITLE
Indicate that publishing can take up to 60 seconds

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#226]
Publishing can take up to 60s because we deploy it to CF workers that distribute it world-wide when publishing from webstudio cloud. When someone installs it differently, publishing won't take this much so this delay should ideally check if the site was actually published and then show success message.

**Comment by kof** [comment]
Alternative is to set up a constant over env variable and show user a message that it may take this amount of time. Isn't as nice though.

**Comment by taylornowotny** [comment]
I'm thinking for the UX we have two options:

1. Show the status inline with the "Publish" button. The button will transition from Publish to Publishing to Published, with an animated icon at each step. This would allow the user to quickly publish using their current settings.
Hovering the button or opening a dropdown will show more advanced options for publishing, like which domain to use. The advanced menu can include the "may take up to 60 seconds" message. A toast will show only if the publishing fails.

2. Show a toast when the "Publish" button is pressed. There will still be an advanced menu but in this case the toast describes the status and the "60 seconds" message. Toast goes away 1s after successful publishing. 

References:
Webflow - Publish button opens a dropdown menu to choose domain. Click 2nd publish button to publish. An advanced menu with toggle options is within the dropdown menu. Toast shown only if publishing fails.
Editor X - Publish button gains a spinny icon when clicked. No further detail. Lasts longer than 60 seconds. 
Framer - Publish button shows a toast when successful. Publishing appears to be instant. Advanced options for publishing are in the site settings.

Thoughts?

**Comment by kof** [comment]
Bit of info that we should be aware of: current url inside designer `/designer/{projectId}` is actually a sharable editable project URL, though its like giving someone full access to the site with no way to revoke that access. Long term we should not allow this and have a more granular control for editable sharable link.

**Comment by kof** [comment]
We have currently these urls we could explicitly show and explain in the share dialog:

1. Share current site in  design mode (same URL as the designer itself for now, but still can be explicitly stated)
2. Share current site in preview mode (what we have now in the share dialog), should explain that this is basically like a production, it will run everything, except that it's not published to the edge infrastructure.
3. Share a clonable site: https://alpha.webstudio.is/rest/project/clone/{domain} this will let you clone a site using the domain. So the user of that URL will have a copy of the site, not affecting the original build

**Comment by kof** [comment]
In addition we should think if we want to enable sharing a specific version of the build. We have the versions in the database (a new one is created when publishing).

It could a menu button or a select box that would allow you to change the version and that would change all the URLs in the share dialog to the specific version

**Comment by taylornowotny** [comment]
"its like giving someone full access to the site with no way to revoke that access. Long term we should not allow this and have a more granular control for editable sharable link."

We need to fix this prior to the beta. I don't think anyone wants another person to have that level of access to their project, even someone trusted.

**Comment by taylornowotny** [comment]
> We have currently these urls we could explicitly show and explain in the share dialog:
> 
>     1. Share current site in  design mode (same URL as the designer itself for now, but still can be explicitly stated)
> 
>     2. Share current site in preview mode (what we have now in the share dialog), should explain that this is basically like a production, it will run everything, except that it's not published to the edge infrastructure.
> 
>     3. Share a clonable site: [https://alpha.webstudio.is/rest/project/clone/{domain}](https://alpha.webstudio.is/rest/project/clone/%7Bdomain%7D) this will let you clone a site using the domain. So the user of that URL will have a copy of the site, not affecting the original build

#2 preview mode - will the person this is shared with have access to the Webstudio UI? Or will they be locked in preview mode?

#1 sharing is design mode - is this giving full edit permissions to anyone with the URL? If so there is no use for this, let's axe it

There should be 3 ways to share:
1 - Share the published site
2 - Share read-only access (ie, locked preview mode)
3- Clone (creates a copy. Does not give access to the user's site)
