### ISSUE TITLE
Explain where the value comes from and allow resetting it

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#29]
When clicking on the property name

- [x] show a popover that explains the property was defined: 
  - inherited from parents
  - set locally
  - token (bound to a token, this will come later once we have done tokens)
- [x] show a link to a full mdn article (we have the links from mdn data)
- [x] ideally show a short simple description (probably has to be written or copied from mdn partially) - lets leave it for later
- [x] reset button that will unset the local value and the value becomes either inherited or defined by default styles or browser styles

Since we don't have designs for it yet, I am attaching examples from webflow. We will have a new design later, it seems easy to change.

<img width="207" alt="Screenshot 2022-11-30 at 12 46 44" src="https://user-images.githubusercontent.com/52824/204800831-e32c27a2-07cf-4533-aee6-a6be2b035c82.png">

<img width="213" alt="Screenshot 2022-11-30 at 12 46 24" src="https://user-images.githubusercontent.com/52824/204800824-f2ab2d2c-88ef-413f-88ec-4a02baaa34e4.png">

**Comment by kof** [comment]
- [ ] reset spacing properties

cc @taylornowotny it seems like we don't have a design for where to put the spacing property reset and also the value origins info

**Comment by taylornowotny** [comment]
> cc @taylornowotny it seems like we don't have a design for where to put the spacing property reset and also the value origins info

Well spacing values don't inherit so there's no need to show the value origins. 

To reset the the property the user can option+click the value.

We may also need to show a clickable reset button. I can add this below the input that pops up. I'll add this to my to-do list under tooltips.
<img width="237" alt="Screenshot 2022-12-23 at 11 16 57 AM" src="https://user-images.githubusercontent.com/86495896/209396411-1c9b2326-7d29-4747-a6d0-d776c1ad1dd3.png">

**Comment by taylornowotny** [comment]
In case it wasn't clear, I am going to re-design tooltips to address the needs outlined in this issue. I am tracking what we need, this is just on hold while I work on tokens

**Comment by TrySound** [comment]
Implementation is ready

**Comment by kof** [comment]
@taylornowotny this is waiting for design

**Comment by taylornowotny** [comment]
Tracking

**Comment by taylornowotny** [comment]
Design is done! #1730
