### ISSUE TITLE
Refactor data loading in designer

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#360]
There're several issues with how we currently load data in designer:

 - Some data is loaded by designer itself, some is loaded by canvas and passed to designer, some might be loaded by both. We don't have a convention of what is the right way.
 - We load data using Remix loaders, which causes two issues:
   - The initial document request is slow for both the canvas document and the designer document
   - The data is duplicated in JSON and HTML, and in the case of the tree it can be really bad if the tree is like 1 MB ([1](https://github.com/webstudio-is/webstudio-designer/issues/346#issuecomment-1291695996), [2](https://github.com/webstudio-is/webstudio-designer/issues/346#issuecomment-1291766435)) 
   
Proposed solution (not final, needs more research / discussion):

 - Load all data in canvas and pass it to designer from there
 - Don't load data using Remix loaders even in canvas

This will also open an interesting possibility of basically swapping up the designer. For example, there're can be an alternative designer in a form of VSCode or Chrome extension that uses the same canvas but the designer UI and features can be very different.

**Comment by kof** [comment]
I think a lot of things have changed , what is still true and what needs to be done? @rpominov @TrySound

**Comment by rpominov** [comment]
The problems described are still valid. 

As for solutions, I'm a bit out of the loop on what @TrySound doing with refactoring data structures and, data flow; and on what @istarkov is doing with TRPC, so not sure.

**Comment by TrySound** [comment]
Now all data is loader in builder and sent to canvas
