### ISSUE TITLE
Update tooltips

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#468]
I have updated the components and specs for tooltips.

Please update the tooltips to match the design and let me know if you have any questions :)

<img width="457" alt="Screenshot 2022-11-18 at 2 12 25 PM" src="https://user-images.githubusercontent.com/86495896/202811913-d6843f1a-ef17-4703-b96d-ffdcd592b482.png">

**Comment by rpominov** [comment]
@taylornowotny I couldn't find this in Figma. I've only found this:

<img width="409" alt="Screenshot 2023-02-02 at 15 06 14" src="https://user-images.githubusercontent.com/825702/216308471-c337965a-b98e-4a79-81f1-1e4ea1c356df.png">

What is the latest design that I should implement?

**Comment by taylornowotny** [comment]
This design update has not been done - other features were prioritized. I’m
designing the props panel right now and next I will do the tooltips

**Comment by rpominov** [comment]
@taylornowotny I'll unassign myself for now, so the issue doesn't show up in my list. Please assign me back when design is ready.
