### ISSUE TITLE
Think about reinitializing controls with key props on selection etc change, or find any other solution

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-builder#564]
Component instances in React are reused and not recreated. 
That cause well-known problem with stateful components,  that the internal state of the component can "leak". 

Example https://codepen.io/istarkov/pen/zYaeemN

```js
const StatefulComponent = ({ value }) => {
  const initialValue = React.useState(() => value);
  return (
    <div>
      <div>Initial value is {initialValue}</div>
      <div>Value is {initialValue}</div>
    </div>
  );
};

const App = () => {
  const [val, setVal] = React.useState(0);
  return (
    <div>
      {val % 2 === 0 ? (
        <StatefulComponent value={10} />
      ) : (
        <StatefulComponent value={20} />
      )}

      <button onClick={() => setVal(val + 1)}>Click me</button>
    </div>
  );
};
```

Independent of what the `val` value is you will see `Initial value is 10`. It "leaked" from the first StatefulComponent to the second.

We already have a bug caused by bad reinitialization of component states
https://github.com/webstudio-is/webstudio-designer/pull/563

And the issue is that such bugs are not rare, and are hard to detect.

Fast approach to solving this is just adding a `key` property to components we want to reinitialize.
i.e. 
```
      {val % 2 === 0 ? (
        <StatefulComponent key={1} value={10} />
      ) : (
        <StatefulComponent key={2}  value={20} />
      )}

```

But can cause some performance issues.

Not fast is testing/testing/testing or avoiding any internal state at all.

What we want now:

To measure the rendering time of the style panel with all open controls (with/without keys) and decide what is best for us.

Pros of keys:
- Components with the internal state can be much simpler.

Cons:
- Performance.
- Non-React way ;-)

**Comment by kof** [comment]
If we change key, we will rerender the controls and it seems this currently leads to blinking controls, its quick but unpleasant, do you also think its because we are rendering the control entirely instead of updating?

**Comment by kof** [comment]
@istarkov still relevant?

**Comment by istarkov** [comment]
Other solution is used here
https://github.com/webstudio-is/webstudio-builder/pull/1383

`useSelectedInstanceKv` - allows to attach state to instances
