### ISSUE TITLE
FOUC when you click link on published site with 2 pages

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-builder#606]
Create 2 pages, and create link from 1st to 2nd.
Publish.
Click link.
See FOUC.

Video:

https://user-images.githubusercontent.com/5077042/207066173-ec172808-a876-4565-b66a-4e3706181b81.mov

FOUC frame:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/5077042/207066143-513f782c-4edb-47e2-80fb-2adca84db17c.png">

**Comment by kof** [comment]
We are using DynamicLinksFunction from remix-utils which doesn't handle the stylesheet loading synchronously/blocking when router switches the pages ... lets see how we can make it behave same way remix's normal link behave
