### ISSUE TITLE
Ability to set a spacing css property to "auto" via unit select

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#667]
Currently user can set to auto by typing "auto" in the input. But we want to let them do it via unit select:

<img width="283" alt="Screenshot 2022-12-20 at 14 59 44" src="https://user-images.githubusercontent.com/825702/208651443-0a7c3014-5858-457d-b8bf-6c9455826c76.png">

↓

<img width="322" alt="Screenshot 2022-12-20 at 14 58 44" src="https://user-images.githubusercontent.com/825702/208651245-6b099f75-fe33-4d37-82f8-d0eb88a65c10.png">

↓

<img width="382" alt="Screenshot 2022-12-20 at 15 00 58" src="https://user-images.githubusercontent.com/825702/208651654-77e6ce22-708b-46f9-b16b-1db2b8e189f7.png">

**Comment by kof** [comment]
In fact there was no final decision yet on what to do with things like auto inside the unit, because as-is is I am not sure this is great. It mixes units with keywords without any separation or concept.

**Comment by rpominov** [comment]
Yeah, also not sure it's a good idea

**Comment by kof** [comment]
In particular we need to decide how we control available units, because some properties don't allow all units. Same for auto/normal should we decide to put them into unit select.

Also since its not a unit select there any more we would need a different internal name for that select component

**Comment by kof** [comment]
was done
