### ISSUE TITLE
Flex and Flex children sections are showing on wrong elements

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#685]
When parent is set on display: flex, we show the flex section and flex child section on it, though, flex child should be only shown for it's children and flex section should not be shown on the child unless it's also set to display flex.

**Comment by istarkov** [comment]
To implement parent style check, the best would be re-use [useStyleInfo](https://github.com/webstudio-is/webstudio-designer/blob/f9996fe1952d64d5994d941150cdc1a93a2805c4/apps/designer/app/designer/features/style-panel/shared/style-info.ts#L158)

But now we have unsynchronized [cssRule here](https://github.com/webstudio-is/webstudio-designer/blob/f9996fe1952d64d5994d941150cdc1a93a2805c4/apps/designer/app/designer/features/style-panel/shared/style-info.ts#L170) 
And cssRule from the tree i.e. `utils.tree.findInstanceById(rootInstance, instanceId)?.cssRules` 

What  cause hacks like 
```ts
  const selectedInstanceCssRules =
    instanceId === selectedInstanceData?.id
      ? selectedInstanceData?.cssRules
      : rootInstance !== undefined && instanceId !== undefined
      ? utils.tree.findInstanceById(rootInstance, instanceId)?.cssRules
      : undefined;
```
As of now @TrySound working on a single source of cssRules values. Better to wait for him to finish, and do the above without hacks

**Comment by rpominov** [comment]
What @istarkov said above is still valid. 

Getting styles for a particular instance is complicated and involves reading `getComputedStyle()` which we do only for the selected instance currently.

I agree that it's better to wait until we simplify how we calculate styles.

**Comment by rpominov** [comment]
Doesn't seem so to me. But @TrySound would know better.

**Comment by TrySound** [comment]
Still requires a bit of refactoring. I think once we done with style sources all of these will be straightforward.
