### ISSUE TITLE
Reset in spacing

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#719]
We have a "reset" functionality for most of the properties in style panel:

<img width="279" alt="Screenshot 2022-12-30 at 11 39 01" src="https://user-images.githubusercontent.com/825702/210046282-13e2fcdf-7158-41e0-95df-0eab9d92d236.png">

We need to find a way to add this to the spacing control somehow:

<img width="232" alt="Screenshot 2022-12-30 at 11 41 19" src="https://user-images.githubusercontent.com/825702/210046481-19a0a2a1-cf52-4dcf-944a-14e1af5230a6.png">

Webflow has a reset button in the input popover:

<img width="260" alt="Screenshot 2022-12-30 at 11 42 09" src="https://user-images.githubusercontent.com/825702/210046557-8f8b098c-ba60-414a-b1c7-bac87278f42d.png">

**Comment by taylornowotny** [comment]
Got it - I will add this when I update the tooltips design soon so it is consistent

**Comment by kof** [comment]
@taylornowotny was this actually designed?

**Comment by taylornowotny** [comment]
No I forgot about this sorry - will do it today

**Comment by taylornowotny** [comment]
This is solved by new tooltips. 

The reset button is in the tooltip same as all other properties.
