### ISSUE TITLE
Size section of the style panel

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#759]
You'll find these designs in the Size Section page in the Webstudio Design Docs file.
<img width="224" alt="Screenshot 2023-01-08 at 11 07 59 PM" src="https://user-images.githubusercontent.com/86495896/211369468-396e6bf1-8879-4dbe-9eb8-08161f1812f4.png">

It's a pretty simple section for now. Should work exactly like Webflow's Size section.
<img width="329" alt="Screenshot 2023-01-08 at 11 07 35 PM" src="https://user-images.githubusercontent.com/86495896/211369471-a5262dea-dcf6-4d5c-81a4-96b922c0682d.png">

- [x] Object Fit is will be added to this section soon, but I need some time to make icons for this. I will make a separate issue for the object fit property when that's done.

**Comment by TrySound** [comment]
Object position looks weird
<img width="227" alt="image" src="https://user-images.githubusercontent.com/5635476/228025345-d3580334-6207-4d1d-8a1d-b81c61278b45.png">

**Comment by kof** [comment]
how do you get it, I have it full size

**Comment by kof** [comment]
oh we broke it on the current main, prod still looks good
