### ISSUE TITLE
Style Source UI

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#807]
Part of Design Tokens User story https://github.com/webstudio-is/webstudio-designer/issues/422

Figma https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?node-id=1013%3A31684&t=3rKaN8KoDwdga6FC-0

## Style Source UI 

- [x] Type a new input with autocomplete
- [x] Select an existing source from a list
- [x] Enter a new source
- [x] Hover the source to see the menu
- [x] Menu provides: Remove, Duplicate, Disable, Edit name
- [x] Drag and drop to reorder
- [x] Click to toggle select/unselect
- [x] Double click to edit name
- [x] Local source can only be disabled, nothing else should be possible
- [x] Hit Backspace to delete the last Source item when you are in the input
- [x] Dropdown menu according to design

## Integration in Style Panel

- [x] Render the Style Source UI where local styles are saved on the Local Style Source
- [x] store style sources in db
- [x] select: always only one is selected
- [x] rename
- [x] remove
- [x] duplicate with auto rename
- [x] sorting with dnd
- [x] merge of all styles into single object
- [x] blue property label for selected style source
- [x] regenerate ids on copy/paste
- [x] when creating or adding a token, it should be selected right away
- [x] A min width on style sources of 32px will leave 16px for the target area
- [x] Cursor should be default when hovering any part of the style source. 
- [x] when dragging source item, prevent selection with user-select: none (could be potentially done over a body globally for any drag/drop over our api)
- [ ] #1576
- [x] delete (a destructive one that actually deletes the source from project)
- [x] orange property label (remote) for not selected style source
- [x] convert to token
- [ ] #1577
- [ ] disabled - persistent/multiplayer
- [x] selected - in-memory when instance switched 
   - select the last one selected
   - window reloaded - selected the latest
- [ ] use InputField component instead of DeprecatedTextField

**Comment by kof** [comment]
Added a todo for a delete menu item for deleting a style source entirely from the project, as opposite to removing, which just removes it from the style source selector. We had this planed for style source manager, but we need to add this to the style source menu, because otherwise its gonna be unusable fast

**Comment by kof** [comment]
To make sure this doesn't go under,  I came across the problem that I sometimes forget to create a token and start working on a local source, but then have no way to copy things over and reset the local.

The best idea so far is "Convert to Token": 
1. copies style properties
2. resets local source
3. creates a token named Local Copy with the previous styles from local

**Comment by taylornowotny** [comment]
Remaining tasks:

States:
- [ ] clicking the state in the SS menu should unselect the state from the SS
https://user-images.githubusercontent.com/86495896/232574253-f93fc053-4172-4ef1-aff6-200190f7406a.mov

Style Sources Input:
- [ ] SSI padding is not consistent with design. When two rows, top and bottom padding looks too small. Should be 4px
Prod:
<img width="227" alt="Screenshot 2023-04-17 at 10 21 23 AM" src="https://user-images.githubusercontent.com/86495896/232574397-2d076c0d-4318-43ee-9942-f18af7bc6aaf.png">
Design:
<img width="267" alt="Screenshot 2023-04-17 at 11 12 49 AM" src="https://user-images.githubusercontent.com/86495896/232574405-de512dd0-703d-47b0-a54b-f3c3ed129e91.png">

- [ ] Border on SSI should use border.main color token
- [ ] remote labels (top priority)
- [ ] add "disable" feature from design

Design to do:
- [ ] Figure out ideal token name wrapping behavior for very long token names (or have a character limit)

**Comment by TrySound** [comment]
>  clicking the state in the SS menu should unselect the state from the SS

the video is broken, can't load. Does it work for you?

**Comment by kof** [comment]
@TrySound video works for me

**Comment by taylornowotny** [comment]
@TrySound if the video won't load for you here's a simple description:

1. Open the token menu to see the list of States
2. Click on a State to apply it
3. Click on the applied State again - this does not remove the State, but it would be better if it did remove the State

That's all. Can we make this happen?

**Comment by kof** [comment]
Lets close this and open a new issue with remaining tasks? This issue has been open for way too long, makes it impossible to see what has been accomplished and when from issues perspective

**Comment by TrySound** [comment]
Splitted last points
