### ISSUE TITLE
New Builder UI Buttons component

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#897]
<img width="250" alt="Screenshot 2023-01-30 at 2 27 22 PM" src="https://user-images.githubusercontent.com/86495896/215610184-a7430de4-c31a-46d5-b848-b43ac60dfe15.png">

This new button component is used in the Builder UI top and left side bars. It is sometimes used as a tab trigger. See docs on the component and the Builder UI docs for details.

**Comment by kof** [comment]
Was actually implemented long time ago as ToolbarToggleItem
