### ISSUE TITLE
Endpoint `/rest/project/${projectId}` for saas should be used for oss published builds

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio-builder#929]
As of now endpoint https://github.com/webstudio-is/webstudio-designer/blob/97fb27c0ceeb979f22eed14567148aa16daedcd3/apps/designer/app/routes/rest/project.$projectId.tsx#L11

Used only for saas deployments and not used at OSS project at all. This causes hard-to-find issues in case of changes. 
We don't know if does endpoint generate the wrong data or if something happening with the SaaS renderer. 

To simplify things we need to use it at OSS to show published builds too, it will be much easier to test.

At saas for edge-preview `dev` mode, we need to use this endpoint too instead of KV storage, to simplify testing.

**Comment by TrySound** [comment]
But how to use endpoint if we access data on ui server route? Import its loader?
