### ISSUE TITLE
UX improvement for Inputs that have both keywords and units

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#956]
The current implementation shows a select menu button on the input when a user starts typing letters, but a unit menu button when the user types numbers (sometimes - it doesn't seem to show up consistently). This is not a good pattern becuase the unit menu should be visible at all times so the user knows that this input accepts numbers and not just key words.

>  My suggestion is similar to the current implementation except that we never show a keyword menu button and always show units (when both are allowed). Keywords can be typed + an autocomplete menu shows, but no keyword select menu.

In the future we could have both menus showing, but the above suggestion would work pretty well and hopefully not require a lot of work.

**Comment by kof** [comment]
This issue is about removing the arrow button when in keywords mode and always showing the unit button instead
