### ISSUE TITLE
New component: Radio

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#963]
This is the “Radio Group Item” within the Radio Group Radix component. Radios are similar to checkboxes except that radio groups can only have one option selected while checkboxes can have multiple.

<img width="385" alt="Screenshot 2023-02-07 at 1 27 29 PM" src="https://user-images.githubusercontent.com/86495896/217370405-5db9f8ca-1abb-4a0f-b1c7-31686e77fb4b.png">

**Comment by taylornowotny** [comment]
hold on, making a small adjustment

**Comment by rpominov** [comment]
@taylornowotny 

It's unfortunate that these circles don't align with pixel grid:

<img width="390" alt="Screenshot 2023-02-23 at 14 27 46" src="https://user-images.githubusercontent.com/825702/220881579-f46254d4-40dd-45ed-bdc7-78f90b018016.png">

Same in the Checkbox component:

<img width="450" alt="Screenshot 2023-02-23 at 14 33 28" src="https://user-images.githubusercontent.com/825702/220882800-f678b916-aee8-46d4-9d45-4c711055654b.png">

I will try to use subpixel values in code, but not sure how well this will work in browsers. I don't have much experience with fractional px values in CSS.
