### ISSUE TITLE
Props panel: control type URL

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-builder#993]
<img width="257" alt="Screenshot 2023-02-10 at 17 08 49" src="https://user-images.githubusercontent.com/825702/218099996-105f7f63-d153-496f-bd08-419fdc04d8ba.png">

- [x] Add control type URL and use it for `Link.href`
- [x] Ability to enter arbitrary url
- [x] Ability to choose a page
- [x] Make sure to call onChange at `blur` when user enters URL

Not essential:

- [ ] Section link
- [x] Email link
- [x] Phone link
- [x] Attachment link

<img width="406" alt="Link Properties" src="https://user-images.githubusercontent.com/825702/218100543-e4de032d-0433-47fc-927f-e2b1271e3ebf.png">

**Comment by rpominov** [comment]
Just realised, we probably should also store `pageId` in props in DB, if page is selected in the control. 

Because if we store path, and user will change path later in the page settings:
- links either stop working, 
- or we'll have to find and update in props.

Also, in Link we should probably use Remix's Link only if a page was selected in control.

**Comment by kof** [comment]
@rpominov for sure, similar to how we do that with images

**Comment by rpominov** [comment]
<img width="247" alt="Screenshot 2023-04-06 at 11 22 11" src="https://user-images.githubusercontent.com/825702/230304131-e412343c-2f66-4d83-b231-95cf9c37a093.png">

@kof @taylornowotny I've just realised that ability to enter URL as an attachment in the URL control doesn't make sense:

We could set the [`<a download />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes) attribute for links in this case, but there're several issues:

 - `download` is not reliable. For example, it doesn't work if `href` points to a different domain.
 - We will need to figure out how to control two props with one control.
 - This will only work if the URL control is used for a link's `href` attribute, but we want our URL control to be general.
 
 So, I'm going to not include the input there, have only the button.

--------------------------

In the File control (the one we use for Image's `source` attribute) ability to enter URL still makes sense.

**Comment by taylornowotny** [comment]
@kof We had talked about this in the context of what Webflow is doing but I don't remember what our conclusion was, do you?

Either way, it's totally ok to leave out the attachment option for now @rpominov
